'use strict';
const {Router}=require('express');
const {requireAdmin}=require('../auth/jwt-auth'),{route}=require('../../utils/ledgerAction');
const service=require('./corrections-service'),rebill=require('./void-rebill');
const args=req=>({accountId:Number(req.user.account_id),actorId:Number(req.user.user_id),body:req.body || {},query:req.query,key:req.get('Idempotency-Key'),invoiceId:req.params.invoiceID,memoId:req.params.memoID,creditId:req.params.creditID,recordId:req.params.recordID});
const invoices=Router();
invoices.get('/:invoiceID/corrections',route(req=>service.context(req.app.get('db'),args(req))));
invoices.post('/:invoiceID/credit-memos',requireAdmin,route(req=>service.memo(req.app.get('db'),args(req))));
invoices.post('/:invoiceID/void-rebill/preview',requireAdmin,route(req=>rebill.preview(req.app.get('db'),args(req))));
invoices.post('/:invoiceID/void-rebill',requireAdmin,route(req=>rebill.commit(req.app.get('db'),args(req))));
const credits=Router();
credits.get('/:creditID/refundable',route(req=>service.refundable(req.app.get('db'),args(req))));
credits.post('/:creditID/refunds',requireAdmin,route(req=>service.refund(req.app.get('db'),args(req))));
const download=kind=>async(req,res)=>{try{const buffer=await service.artifact(req.app.get('db'),args(req),kind);res.type('pdf').set('Content-Disposition','attachment; filename="correction.pdf"').send(buffer);}catch(e){const status=e.statusCode || 500;res.status(status).send({status,message:status===500?'Unable to retrieve the archived document. Please retry.':e.message});}};
const memos=Router();
memos.get('/',route(req=>service.list(req.app.get('db'),args(req),'memos')));
memos.get('/reversals/:recordID/pdf',download('reversals'));
memos.get('/:recordID',route(req=>service.detail(req.app.get('db'),args(req),'memos')));
memos.get('/:recordID/pdf',download('memos'));
memos.post('/:memoID/reversals',requireAdmin,route(req=>service.reverseMemo(req.app.get('db'),args(req))));
const refunds=Router();
refunds.get('/',route(req=>service.list(req.app.get('db'),args(req),'refunds')));
refunds.get('/:recordID',route(req=>service.detail(req.app.get('db'),args(req),'refunds')));
refunds.get('/:recordID/pdf',download('refunds'));
const voids=Router();voids.get('/:recordID/pdf',download('void'));
module.exports={invoices,credits,memos,refunds,voids};
