version: '3.9'

networks:
   ds2_network:
      external: true

services:
   ds2_backend:
      container_name: DS2-Backend
      image: marine1232/ds2-backend:latest
      environment:
         - TZ=America/Phoenix
      env_file:
         - .env
      volumes:
         - './:/app'
         - '/app/node_modules'
      ports:
         - '8003:8003'
      restart: always
      networks:
         - ds2_network
