-- Create table to hold AI-generated categorization suggestions for timesheet entries
CREATE TABLE ai_time_tracker_transaction_suggestions (
     suggestion_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     timesheet_entry_id integer NOT NULL REFERENCES timesheet_entries(timesheet_entry_id) ON DELETE CASCADE,
     sanitized_notes text NOT NULL,
     suggested_category text,
     suggested_job_category_id integer REFERENCES customer_job_categories(customer_job_category_id),
     suggested_job_type_id integer REFERENCES customer_job_types(job_type_id),
     suggested_general_work_description_id integer REFERENCES customer_general_work_descriptions(general_work_description_id),
     suggested_entity text,
     suggested_customer_id integer REFERENCES customers(customer_id),
     suggested_customer_display_name text,
     ai_confidence numeric(5,4),
     ai_reason text,
     ai_payload jsonb,
     status varchar(30) NOT NULL DEFAULT 'pending',
     source varchar(30) NOT NULL DEFAULT 'ai',
     created_at timestamp NOT NULL DEFAULT NOW(),
     updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX ai_time_tracker_transaction_suggestions_entry_idx
     ON ai_time_tracker_transaction_suggestions(timesheet_entry_id);

CREATE INDEX ai_time_tracker_transaction_suggestions_account_idx
     ON ai_time_tracker_transaction_suggestions(account_id);
