CREATE TABLE time_tracker_staff (
   id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   user_id integer NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
   is_active boolean NOT NULL DEFAULT TRUE,
   created_at timestamp DEFAULT NOW()
);

ALTER TABLE time_tracker_staff
   ADD CONSTRAINT time_tracker_staff_unique_user UNIQUE (user_id);
