-- Create audit table for AI requests
CREATE TABLE IF NOT EXISTS ai_request_logs(
     ai_request_log_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     request_id varchar(64) NOT NULL,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     user_id integer,
     provider varchar(50) NOT NULL DEFAULT 'openai',
     feature varchar(100) NOT NULL,
     model varchar(100),
     model_cost_tier varchar(50),
     entries_count integer,
     sample_entry_ids jsonb,
     status varchar(30) NOT NULL DEFAULT 'prepared',
     error_message text,
     started_at timestamp NOT NULL DEFAULT NOW(),
     completed_at timestamp,
     created_at timestamp NOT NULL DEFAULT NOW(),
     updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ai_request_logs_request_id_idx ON ai_request_logs(request_id);

CREATE INDEX IF NOT EXISTS ai_request_logs_account_idx ON ai_request_logs(account_id);

CREATE INDEX IF NOT EXISTS ai_request_logs_started_idx ON ai_request_logs(started_at);

