CREATE TABLE account_automation_settings (
   account_automation_setting_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
   automation_key varchar(100) NOT NULL,
   is_enabled boolean NOT NULL DEFAULT TRUE,
   created_at timestamp DEFAULT NOW(),
   updated_at timestamp DEFAULT NOW()
);

ALTER TABLE account_automation_settings
   ADD CONSTRAINT account_automation_settings_unique_account_automation UNIQUE (account_id, automation_key);
