-- Create table to capture training examples for AI category suggestions
-- Contains no PII fields. Only category and sanitized context.
CREATE TABLE IF NOT EXISTS ai_category_training_examples(
     training_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     -- Linkage for provenance (safe IDs only)
     timesheet_entry_id integer REFERENCES timesheet_entries(timesheet_entry_id) ON DELETE SET NULL,
     transaction_id integer REFERENCES customer_transactions(transaction_id) ON DELETE SET NULL,
     -- Categories
     original_category text,
     suggested_category text,
     final_category text NOT NULL,
     -- AI metadata (non-PII)
     ai_reason text,
     ai_confidence numeric(5, 4),
     ai_source varchar(30) DEFAULT 'ai',
     -- Notes context
     original_notes text,
     sanitized_notes text,
     -- Additional non-PII context useful for future guesses
     -- e.g., entry duration in minutes and generic entity label
     duration_minutes integer,
     entity text,
     -- Upload tracking to external vector store
     uploaded_to_vector_store boolean NOT NULL DEFAULT FALSE,
     uploaded_at timestamp NULL,
     created_at timestamp NOT NULL DEFAULT NOW(),
     updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ai_category_training_examples_account_idx ON ai_category_training_examples(account_id);

CREATE INDEX IF NOT EXISTS ai_category_training_examples_uploaded_idx ON ai_category_training_examples(uploaded_to_vector_store, created_at);

CREATE INDEX IF NOT EXISTS ai_category_training_examples_txn_idx ON ai_category_training_examples(transaction_id);

