-- Migration 007: Create customer_payments_processed table
-- Stores processed payment records extracted from uploaded payment images/PDFs
-- by the Process_Payment_Images Lambda pipeline.

DROP TABLE IF EXISTS customer_payments_processed;

CREATE TABLE customer_payments_processed (
    payment_id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id              integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
    customer_id             integer REFERENCES customers(customer_id) ON DELETE SET NULL,
    matched_customer_id     integer REFERENCES customers(customer_id) ON DELETE SET NULL,
    customer_name           text NOT NULL DEFAULT '',
    matched_customer_name   text NOT NULL DEFAULT '',
    customer_invoice_id     text NOT NULL DEFAULT '',
    customer_job_id         text NOT NULL DEFAULT '',
    retainer_id             text NOT NULL DEFAULT '',
    payment_amount          numeric(12, 2),
    payment_reference_number text NOT NULL DEFAULT '',
    payment_date            date,
    form_of_payment         varchar(30) NOT NULL DEFAULT '',
    is_transaction_billable boolean NOT NULL DEFAULT TRUE,
    is_payment_processed    boolean NOT NULL DEFAULT false,
    deleted                 boolean NOT NULL DEFAULT false,
    date_processed          timestamp,
    note                    text NOT NULL DEFAULT '',
    source_file             text NOT NULL DEFAULT '',
    file_location           text NOT NULL DEFAULT '',
    created_at              timestamp NOT NULL DEFAULT NOW(),
    created_by_user_id      integer NOT NULL DEFAULT 1
);

-- Prevent duplicate inserts for the same file/customer/amount combination
CREATE UNIQUE INDEX customer_payments_processed_dedup_idx
    ON customer_payments_processed (source_file, customer_name, payment_amount);

CREATE INDEX customer_payments_processed_account_idx
    ON customer_payments_processed (account_id);

CREATE INDEX customer_payments_processed_customer_idx
    ON customer_payments_processed (customer_id);

CREATE INDEX customer_payments_processed_date_idx
    ON customer_payments_processed (payment_date);

CREATE INDEX customer_payments_processed_status_idx
    ON customer_payments_processed (is_payment_processed, deleted);
