CREATE TABLE ai_call_log(
   ai_call_log_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   request_id varchar(64) NOT NULL,
   account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
   user_id integer NULL REFERENCES users(user_id) ON DELETE SET NULL,
   timesheet_entry_id integer NULL
      REFERENCES timesheet_entries(timesheet_entry_id) ON DELETE SET NULL,
   provider varchar(30) NOT NULL DEFAULT 'bedrock',
   feature varchar(60) NOT NULL,
   model_id varchar(120) NOT NULL,
   input_tokens integer,
   output_tokens integer,
   cost_usd numeric(10, 6),
   latency_ms integer,
   status varchar(20) NOT NULL DEFAULT 'ok',
   error_message text,
   s3_log_key text,
   created_at timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX ai_call_log_account_idx
   ON ai_call_log(account_id, created_at DESC);
CREATE INDEX ai_call_log_entry_idx
   ON ai_call_log(timesheet_entry_id) WHERE timesheet_entry_id IS NOT NULL;

CREATE TABLE notifications(
   notification_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
   user_id integer NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
   type varchar(60) NOT NULL,
   title varchar(200) NOT NULL,
   body text,
   payload jsonb NOT NULL DEFAULT '{}'::jsonb,
   read_at timestamp NULL,
   expires_at timestamp NULL,
   created_at timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX notifications_user_unread_idx
   ON notifications(user_id, created_at DESC) WHERE read_at IS NULL;

CREATE TABLE template_downloads(
   template_download_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
   user_id integer NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
   customer_count integer NOT NULL,
   employee_count integer NOT NULL,
   category_count integer NOT NULL,
   downloaded_at timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX template_downloads_account_idx
   ON template_downloads(account_id, downloaded_at DESC);

ALTER TABLE accounts
   ADD COLUMN ai_daily_cost_cap_usd numeric(8, 2) NULL;
