-- Capture human reviewer corrections to AI-applied transactions across ANY field
-- (customer_id, customer_job_id, general_work_description_id, is_transaction_billable, etc.).
-- The existing ai_category_training_examples table only writes when the work-description
-- changes; this table captures the full picture so we can train on customer/job/billable
-- corrections too.
CREATE TABLE IF NOT EXISTS ai_reviewer_corrections(
     correction_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     -- Linkage (safe IDs only)
     transaction_id integer REFERENCES customer_transactions(transaction_id) ON DELETE SET NULL,
     timesheet_entry_id integer REFERENCES timesheet_entries(timesheet_entry_id) ON DELETE SET NULL,
     reviewer_user_id integer REFERENCES users(user_id) ON DELETE SET NULL,
     -- Which field changed and the values
     field_name varchar(64) NOT NULL,
     original_value text,
     final_value text,
     -- For human-readable training context, the labels (resolved at write time so future
     -- queries don't need joins):
     original_label text,
     final_label text,
     -- PII-redacted notes from the transaction at time-of-correction. Required for the
     -- few-shot loader to consider this row.
     sanitized_notes text,
     created_at timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ai_reviewer_corrections_account_idx ON ai_reviewer_corrections(account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ai_reviewer_corrections_field_idx ON ai_reviewer_corrections(account_id, field_name, created_at DESC);
CREATE INDEX IF NOT EXISTS ai_reviewer_corrections_txn_idx ON ai_reviewer_corrections(transaction_id);
