CREATE TABLE account_audits(
   audit_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
   customer_id integer NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
   run_by_user_id integer NULL REFERENCES users(user_id) ON DELETE SET NULL,
   run_by_display_name varchar(100) NOT NULL,
   status varchar(20) NOT NULL DEFAULT 'completed',
   total_invoiced numeric(12, 2) NOT NULL DEFAULT 0,
   total_paid numeric(12, 2) NOT NULL DEFAULT 0,
   total_transactions numeric(12, 2) NOT NULL DEFAULT 0,
   total_writeoffs numeric(12, 2) NOT NULL DEFAULT 0,
   outstanding_invoices numeric(12, 2) NOT NULL DEFAULT 0,
   unbilled_billable numeric(12, 2) NOT NULL DEFAULT 0,
   unbilled_payments numeric(12, 2) NOT NULL DEFAULT 0,
   unbilled_writeoffs numeric(12, 2) NOT NULL DEFAULT 0,
   audit_balance numeric(12, 2) NOT NULL DEFAULT 0,
   strict_ledger_balance numeric(12, 2) NOT NULL DEFAULT 0,
   discrepancy_count integer NOT NULL DEFAULT 0,
   discrepancies jsonb NOT NULL DEFAULT '[]'::jsonb,
   ledger jsonb NOT NULL DEFAULT '[]'::jsonb,
   summary jsonb NOT NULL DEFAULT '{}'::jsonb,
   notes text,
   error_message text,
   created_at timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX account_audits_account_idx
   ON account_audits(account_id, created_at DESC);
CREATE INDEX account_audits_customer_idx
   ON account_audits(customer_id, created_at DESC);
