-- Agreed-rate cards: the rate the firm agreed to charge a client for a year
-- (engagement letter). The Client Rates page compares this against the
-- realized rate (time billings ÷ hours) to show variance.
CREATE TABLE IF NOT EXISTS customer_rate_agreements (
   rate_agreement_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
   customer_id integer NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
   agreement_year integer NOT NULL,
   agreed_rate DECIMAL(10, 2) NOT NULL,
   notes text,
   created_at timestamp DEFAULT NOW(),
   created_by_user_id integer NOT NULL REFERENCES users(user_id),
   UNIQUE (account_id, customer_id, agreement_year)
);

CREATE INDEX IF NOT EXISTS idx_rate_agreements_customer
   ON customer_rate_agreements (customer_id, agreement_year);
