-- 019: ledger data normalization (2026-09-22 review; 2026-09-23 revision — fail-closed
-- total_payments flips + row-level audit evidence for every changed field). Idempotent; safe
-- to re-run.
--
-- Apply to dev with `npm run migrate`; apply to PROD BY HAND after review:
--   PGPASSWORD=... psql -h <rds> -U <user> -d ds2_prod -X -1 -v ON_ERROR_STOP=1 -f migrations/019.ledger_data_normalization.sql
-- Take a backup first. The command above COMMITs automatically on success.
-- Inspect counts in a separate BEGIN/file/ROLLBACK rehearsal before the committing run (see
-- migrations/README.md).
--
-- FILE CONTRACT (see migrations/README.md): this file is PLAIN SQL — no BEGIN/COMMIT and no
-- psql meta-commands. `scripts/migrate.js` wraps it in its own transaction; a by-hand run needs
-- `psql -X -1` (single-transaction mode) to get the same wrapping — the LOCK TABLE below only
-- protects the rest of this file when it does. Don't add BEGIN/COMMIT back: that would end
-- whichever wrapper transaction is supposed to own this file's atomicity.
--
-- 1. transaction_type casing. The auto-ingest and manual-submission paths wrote
--    'time' (5,130 prod rows) while the UI writes 'Time'; every analytics and
--    employee-time query compares against 'Time' exactly, so those hours and
--    dollars were invisible to reports. The API now normalises on write.
-- 2. Literal 'null' / 'undefined' strings produced by `String(x) || ''` mappers
--    (33,129 transaction notes in prod).
-- 3. customer_invoices.total_payments sign — FAIL CLOSED (2026-09-23 revision). The June-2026
--    code stores the column as a NEGATIVE net (same sign as customer_payments rows); legacy
--    rows stored a POSITIVE magnitude (918 parents in prod). A flip used to be driven by
--    arithmetic equality alone (stored value == magnitude of payments tagged to the chain, no
--    positive/reversal rows) — but arithmetic equality is not proof of correct attribution: a
--    reversal payment tagged to a DIFFERENT root, or a child invoice whose payments roll up to
--    a root owned by a DIFFERENT customer, can produce the exact same arithmetic match while
--    flipping the wrong row (round-3 review, finding F2 — reproduced against fixtures with
--    both shapes). A row now flips ONLY when it appears in the _m019_reviewed manifest below
--    (account_id, customer_id, root_id, the old total, the signed net, and the exact set of
--    payment ids all pre-declared) AND the live data still matches every one of those expected
--    values exactly AND the chain has no reversal event of its own (s.positive_events = 0) AND
--    no OTHER payment or linked child row anywhere in the chain belongs to a different
--    account/customer (the NOT EXISTS ownership check below — follow-up finding N4: a root's
--    OWN arithmetic group can match exactly while a foreign payment still sits elsewhere in the
--    same chain via a child invoice, which is exactly the misattribution shape this migration
--    exists to stop flipping). The manifest starts EMPTY — "accountant-reviewed rows go here" —
--    so this migration flips NOTHING in prod until a reviewed block is pasted in. Generate the
--    accountant CSV and the matching SQL INSERT block with
--    `node scripts/review-2026-09/positive-total-payments-manifest.js` (read-only; the generator
--    applies the same reversal and ownership quarantine, so nothing it lists can fail these
--    checks unless the live data changed between generation and review). Child snapshots are
--    never touched (they need event-time reconciliation).
-- 4. Row-level audit evidence. Every field this migration changes — not just total_payments —
--    is logged to ledger_normalization_log with its before/after value, idempotently: the
--    before-image capture below only ever selects rows still in the "before" (unfixed) state,
--    so a rerun that finds nothing left to fix logs nothing new.

-- Permanent evidence of every row this migration changed (the accountant's manifest; also what
-- you would use to revert a single row).
CREATE TABLE IF NOT EXISTS ledger_normalization_log (
   log_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   migration text NOT NULL,
   table_name text NOT NULL,
   row_id integer NOT NULL,
   account_id integer,
   customer_id integer,
   column_name text NOT NULL,
   old_value text,
   new_value text,
   applied_at timestamptz NOT NULL DEFAULT now()
);

-- Keep the before-images below stable through their UPDATEs and the audit INSERT — nothing else
-- may change these four tables mid-migration. Held for the rest of the wrapper transaction
-- (see FILE CONTRACT above — this is why the file cannot supply its own BEGIN/COMMIT).
LOCK TABLE customer_transactions, customer_payments, customer_writeoffs, customer_invoices
   IN SHARE ROW EXCLUSIVE MODE;

-- Every field-level change this file is about to make, captured BEFORE any UPDATE runs. A
-- rerun only ever finds rows still in the "before" state here — an already-fixed row no longer
-- matches these WHERE clauses — which is what makes the log insert below idempotent for these
-- columns with no separate dedup check needed.
CREATE TEMP TABLE _m019_before ON COMMIT DROP AS
SELECT 'customer_transactions'::text AS table_name, transaction_id AS row_id, account_id, customer_id,
       'transaction_type'::text AS column_name, transaction_type::text AS old_value,
       CASE transaction_type WHEN 'time' THEN 'Time' ELSE 'Charge' END::text AS new_value
FROM customer_transactions WHERE transaction_type IN ('time', 'charge')
UNION ALL
SELECT 'customer_transactions', transaction_id, account_id, customer_id, 'note', note, NULL
FROM customer_transactions WHERE note IN ('null', 'undefined')
UNION ALL
SELECT 'customer_transactions', transaction_id, account_id, customer_id, 'detailed_work_description', detailed_work_description, NULL
FROM customer_transactions WHERE detailed_work_description IN ('null', 'undefined')
UNION ALL
SELECT 'customer_payments', payment_id, account_id, customer_id, 'note', note, NULL
FROM customer_payments WHERE note IN ('null', 'undefined')
UNION ALL
SELECT 'customer_payments', payment_id, account_id, customer_id, 'payment_reference_number', payment_reference_number, NULL
FROM customer_payments WHERE payment_reference_number IN ('null', 'undefined')
UNION ALL
SELECT 'customer_writeoffs', writeoff_id, account_id, customer_id, 'note', note, NULL
FROM customer_writeoffs WHERE note IN ('null', 'undefined');

CREATE TEMP TABLE _m019_counts (step text, rows_affected bigint) ON COMMIT DROP;

WITH u AS (UPDATE customer_transactions SET transaction_type = 'Time' WHERE transaction_type = 'time' RETURNING 1)
INSERT INTO _m019_counts SELECT 'transaction_type time->Time', count(*) FROM u;
WITH u AS (UPDATE customer_transactions SET transaction_type = 'Charge' WHERE transaction_type = 'charge' RETURNING 1)
INSERT INTO _m019_counts SELECT 'transaction_type charge->Charge', count(*) FROM u;

WITH u AS (UPDATE customer_transactions SET note = NULL WHERE note IN ('null', 'undefined') RETURNING 1)
INSERT INTO _m019_counts SELECT 'transactions.note literal null', count(*) FROM u;
WITH u AS (UPDATE customer_transactions SET detailed_work_description = NULL WHERE detailed_work_description IN ('null', 'undefined') RETURNING 1)
INSERT INTO _m019_counts SELECT 'transactions.detailed_work_description literal null', count(*) FROM u;
WITH u AS (UPDATE customer_payments SET note = NULL WHERE note IN ('null', 'undefined') RETURNING 1)
INSERT INTO _m019_counts SELECT 'payments.note literal null', count(*) FROM u;
WITH u AS (UPDATE customer_payments SET payment_reference_number = NULL WHERE payment_reference_number IN ('null', 'undefined') RETURNING 1)
INSERT INTO _m019_counts SELECT 'payments.payment_reference_number literal null', count(*) FROM u;
WITH u AS (UPDATE customer_writeoffs SET note = NULL WHERE note IN ('null', 'undefined') RETURNING 1)
INSERT INTO _m019_counts SELECT 'writeoffs.note literal null', count(*) FROM u;

-- Row-level before/after evidence for every field touched above (F3). Inserted once, from the
-- before-image snapshot captured under lock at the top of this file — see the idempotency note
-- there.
INSERT INTO ledger_normalization_log (migration, table_name, row_id, account_id, customer_id, column_name, old_value, new_value)
SELECT '019', table_name, row_id, account_id, customer_id, column_name, old_value, new_value
FROM _m019_before;

-- ── total_payments sign flip: FAIL CLOSED (F2) ───────────────────────────────────────────────
-- Populated ONLY from an independently reviewed manifest generated by
-- scripts/review-2026-09/positive-total-payments-manifest.js. Empty here means quarantine:
-- nothing below flips until a reviewed block is pasted in.
CREATE TEMP TABLE _m019_reviewed (
   account_id integer NOT NULL,
   customer_id integer NOT NULL,
   root_id integer PRIMARY KEY,
   expected_old_total numeric NOT NULL,
   expected_signed_net numeric NOT NULL,
   expected_payment_ids integer[] NOT NULL
) ON COMMIT DROP;

-- accountant-reviewed rows go here
-- INSERT INTO _m019_reviewed (account_id, customer_id, root_id, expected_old_total, expected_signed_net, expected_payment_ids) VALUES
--    (1, 123, 456, 500.00, -500.00, ARRAY[789, 790]);

WITH resolved AS (
   SELECT p.payment_id, p.account_id, p.customer_id, p.payment_amount,
          COALESCE(i.parent_invoice_id, i.customer_invoice_id) AS root_id
   FROM customer_payments p
   JOIN customer_invoices i ON i.customer_invoice_id = p.customer_invoice_id
   WHERE i.account_id = p.account_id AND i.customer_id = p.customer_id
), sums AS (
   SELECT root_id, account_id, customer_id, array_agg(payment_id ORDER BY payment_id) AS payment_ids,
          SUM(payment_amount) AS signed_net, SUM(ABS(payment_amount)) AS magnitude,
          COUNT(*) FILTER (WHERE payment_amount > 0) AS positive_events
   FROM resolved GROUP BY root_id, account_id, customer_id
), u AS (
   UPDATE customer_invoices i
   SET total_payments = s.signed_net
   FROM sums s
   JOIN _m019_reviewed m
      ON m.root_id = s.root_id
     AND m.account_id = s.account_id
     AND m.customer_id = s.customer_id
     AND m.expected_payment_ids = s.payment_ids
     AND m.expected_signed_net = s.signed_net
   WHERE i.customer_invoice_id = s.root_id
     AND i.parent_invoice_id IS NULL
     AND i.account_id = s.account_id AND i.customer_id = s.customer_id
     AND i.total_payments = m.expected_old_total
     AND i.total_payments > 0
     AND i.total_payments = s.magnitude
     -- N6: no reversal/positive event anywhere in this root's OWN (account/customer-scoped)
     -- resolved-payment group — a hand-edited manifest row can't sneak a positive-only chain
     -- through even if every other predicate above happens to match.
     AND s.positive_events = 0
     -- N4: quarantine any chain with conflicting ownership — a payment, or a payment reachable
     -- through a linked child invoice, whose account_id/customer_id differs from this root's.
     -- Arithmetic equality on the root's OWN group (checked above) is not enough: a foreign
     -- payment can sit elsewhere in the same chain via a child invoice while the root's own
     -- group still matches exactly (see the header comment, finding N4).
     -- R2 fix (2026-09 second follow-up review): start from the LINKED INVOICES and LEFT JOIN
     -- their payments, not the other way around. Starting from customer_payments (an inner join)
     -- made a foreign-owned child invoice with NO payment of its own invisible to this check —
     -- there was no "bad" payment row to find, so it flipped anyway. A same-owner child with no
     -- payment must stay eligible: bad.payment_id IS NULL means "no payment to compare", never
     -- itself a conflict.
     AND NOT EXISTS (
            SELECT 1 FROM customer_invoices linked
            LEFT JOIN customer_payments bad ON bad.customer_invoice_id = linked.customer_invoice_id
            WHERE COALESCE(linked.parent_invoice_id, linked.customer_invoice_id) = i.customer_invoice_id
              AND ((bad.payment_id IS NOT NULL
                    AND (bad.account_id, bad.customer_id) IS DISTINCT FROM (i.account_id, i.customer_id))
                OR (linked.account_id, linked.customer_id) IS DISTINCT FROM (i.account_id, i.customer_id))
         )
   RETURNING i.customer_invoice_id, i.account_id, i.customer_id, s.magnitude AS old_value, i.total_payments AS new_value
), logged AS (
   INSERT INTO ledger_normalization_log (migration, table_name, row_id, account_id, customer_id, column_name, old_value, new_value)
   SELECT '019', 'customer_invoices', customer_invoice_id, account_id, customer_id, 'total_payments', old_value::text, new_value::text FROM u
   RETURNING 1
)
INSERT INTO _m019_counts SELECT 'invoices.total_payments positive->signed net (reviewed manifest rows only; see ledger_normalization_log)', count(*) FROM logged;

-- Parents still positive (never in the manifest, or in it but not matching live data): need
-- accountant review. Listed, not just counted, and deduplicated explicitly (unlike the columns
-- above, these rows' state never changes, so "no longer matches the before WHERE" can't do the
-- dedup for us).
INSERT INTO ledger_normalization_log (migration, table_name, row_id, account_id, customer_id, column_name, old_value, new_value)
SELECT '019-review', 'customer_invoices', i.customer_invoice_id, i.account_id, i.customer_id, 'total_payments', i.total_payments::text, NULL
FROM customer_invoices i
WHERE i.parent_invoice_id IS NULL AND i.total_payments > 0
  AND NOT EXISTS (
     SELECT 1 FROM ledger_normalization_log l
     WHERE l.migration = '019-review' AND l.table_name = 'customer_invoices' AND l.row_id = i.customer_invoice_id
  );
INSERT INTO _m019_counts
SELECT 'invoices.total_payments still positive (review list in ledger_normalization_log, migration=019-review)', count(*) FROM customer_invoices WHERE parent_invoice_id IS NULL AND total_payments > 0;

SELECT * FROM _m019_counts ORDER BY step;
