-- Issued evidence is append-only. No existing account/business rows are changed.
CREATE TABLE IF NOT EXISTS invoice_lock_policy (
 singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
 legacy_before timestamp NOT NULL DEFAULT clock_timestamp()
);
INSERT INTO invoice_lock_policy(singleton) VALUES(true) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS invoice_issues (
 account_id integer NOT NULL REFERENCES accounts(account_id),
 invoice_id integer NOT NULL REFERENCES customer_invoices(customer_invoice_id),
 customer_id integer NOT NULL REFERENCES customers(customer_id),
 invoice_number text NOT NULL,
 issued_at timestamp NOT NULL DEFAULT clock_timestamp(),
 issued_by integer NOT NULL REFERENCES users(user_id),
 artifact_key text NOT NULL,
 payload jsonb NOT NULL,
 PRIMARY KEY(account_id, invoice_id)
);
CREATE TABLE IF NOT EXISTS invoice_statement_members (
 account_id integer NOT NULL,
 invoice_id integer NOT NULL,
 table_name text NOT NULL CHECK(table_name IN ('customer_invoices','customer_transactions','customer_payments','customer_writeoffs','customer_retainers_and_prepayments')),
 record_id integer NOT NULL,
 snapshot jsonb NOT NULL,
 PRIMARY KEY(account_id, invoice_id, table_name, record_id),
 FOREIGN KEY(account_id,invoice_id) REFERENCES invoice_issues(account_id,invoice_id)
);
CREATE INDEX IF NOT EXISTS invoice_member_record_idx ON invoice_statement_members(account_id,table_name,record_id);
CREATE TABLE IF NOT EXISTS invoice_exceptions (
 exception_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id integer NOT NULL,
 invoice_id integer NOT NULL,
 condition text NOT NULL,
 reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 2000),
 state text NOT NULL DEFAULT 'flagged' CHECK(state IN ('flagged','reversed','resolved_revision','resolved_roll_forward','cancelled')),
 created_by integer NOT NULL REFERENCES users(user_id),
 created_at timestamp NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY(account_id,invoice_id) REFERENCES invoice_issues(account_id,invoice_id),
 UNIQUE(account_id,invoice_id,exception_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS invoice_one_active_exception ON invoice_exceptions(account_id,invoice_id) WHERE state IN ('flagged','reversed');
CREATE TABLE IF NOT EXISTS invoice_exception_payments (
 account_id integer NOT NULL,
 invoice_id integer NOT NULL,
 exception_id integer NOT NULL,
 payment_id integer NOT NULL REFERENCES customer_payments(payment_id),
 reversal_id integer REFERENCES customer_payments(payment_id),
 amount numeric(12,2) NOT NULL CHECK(amount > 0),
 PRIMARY KEY(exception_id,payment_id),
 FOREIGN KEY(account_id,invoice_id,exception_id) REFERENCES invoice_exceptions(account_id,invoice_id,exception_id)
);
CREATE TABLE IF NOT EXISTS invoice_revisions (
 account_id integer NOT NULL,
 invoice_id integer NOT NULL,
 revision integer NOT NULL CHECK(revision >= 0),
 exception_id integer REFERENCES invoice_exceptions(exception_id),
 artifact_key text NOT NULL,
 issued_amount numeric(12,2) NOT NULL,
 payload jsonb NOT NULL,
 created_by integer NOT NULL REFERENCES users(user_id),
 created_at timestamp NOT NULL DEFAULT clock_timestamp(),
 PRIMARY KEY(account_id,invoice_id,revision),
 FOREIGN KEY(account_id,invoice_id) REFERENCES invoice_issues(account_id,invoice_id)
);
CREATE TABLE IF NOT EXISTS invoice_history (
 history_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id integer NOT NULL,
 invoice_id integer NOT NULL,
 exception_id integer REFERENCES invoice_exceptions(exception_id),
 event text NOT NULL,
 actor_id integer NOT NULL REFERENCES users(user_id),
 created_at timestamp NOT NULL DEFAULT clock_timestamp(),
 detail jsonb NOT NULL DEFAULT '{}'::jsonb,
 FOREIGN KEY(account_id,invoice_id) REFERENCES invoice_issues(account_id,invoice_id)
);

-- Returns an invoice number, never another tenant's metadata. Historical
-- artifact-bearing parents are conservative locks without a business-row backfill.
CREATE OR REPLACE FUNCTION ds2_locked_invoice(t text, rid integer, aid integer)
RETURNS text LANGUAGE plpgsql STABLE AS $$
DECLARE n text; r jsonb; key text;
BEGIN
 SELECT i.invoice_number INTO n FROM invoice_statement_members m JOIN invoice_issues i USING(account_id,invoice_id)
 WHERE m.account_id=aid AND m.table_name=t AND m.record_id=rid ORDER BY i.issued_at,m.invoice_id LIMIT 1;
 IF n IS NOT NULL THEN RETURN n; END IF;
 key := CASE t WHEN 'customer_invoices' THEN 'customer_invoice_id' WHEN 'customer_transactions' THEN 'transaction_id'
 WHEN 'customer_payments' THEN 'payment_id' WHEN 'customer_writeoffs' THEN 'writeoff_id'
 WHEN 'customer_retainers_and_prepayments' THEN 'retainer_id' ELSE NULL END;
 IF key IS NULL THEN RETURN NULL; END IF;
 EXECUTE format('SELECT to_jsonb(r) FROM %I r WHERE account_id=$1 AND %I=$2',t,key) INTO r USING aid,rid;
 IF r IS NULL THEN RETURN NULL; END IF;
 SELECT p.invoice_number INTO n FROM customer_invoices p, invoice_lock_policy policy
 WHERE p.account_id=aid AND p.customer_id=(r->>'customer_id')::integer AND p.parent_invoice_id IS NULL
 AND p.created_at < policy.legacy_before AND NULLIF(p.invoice_file_location,'') IS NOT NULL
 AND ((t='customer_invoices' AND p.customer_invoice_id=rid)
 OR (t IN ('customer_transactions','customer_payments','customer_writeoffs') AND p.customer_invoice_id=(r->>'customer_invoice_id')::integer)
 OR (t <> 'customer_transactions' AND (r->>'created_at')::timestamp <= p.created_at))
 ORDER BY p.created_at,p.customer_invoice_id LIMIT 1;
 RETURN n;
END $$;

CREATE OR REPLACE FUNCTION ds2_guard_sent_record() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE r jsonb; n text; key text; cid integer; aid integer;
BEGIN
 r := CASE WHEN TG_OP='DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
 cid := (r->>'customer_id')::integer; aid := (r->>'account_id')::integer;
 -- Serializes raw imports with the application's finalize boundary too.
 PERFORM customer_id FROM customers WHERE account_id=aid AND customer_id=cid FOR NO KEY UPDATE;
 key := TG_ARGV[0];
 IF TG_OP <> 'INSERT' THEN
   n := ds2_locked_invoice(TG_TABLE_NAME,(to_jsonb(OLD)->>key)::integer,OLD.account_id);
 END IF;
 IF n IS NULL AND TG_TABLE_NAME IN ('customer_transactions','customer_payments','customer_writeoffs') AND TG_OP <> 'DELETE' THEN
   IF TG_OP='INSERT' OR (to_jsonb(OLD)->>'customer_invoice_id') IS DISTINCT FROM (r->>'customer_invoice_id') THEN
     n := ds2_locked_invoice('customer_invoices',(r->>'customer_invoice_id')::integer,aid);
   END IF;
 END IF;
 IF n IS NULL AND TG_OP='INSERT' AND TG_TABLE_NAME <> 'customer_transactions' THEN
   SELECT invoice_number INTO n FROM invoice_issues WHERE account_id=aid AND customer_id=cid
   AND (r->>'created_at')::timestamp <= issued_at ORDER BY issued_at DESC LIMIT 1;
 END IF;
 IF n IS NOT NULL THEN RAISE EXCEPTION 'locked: part of sent invoice %', n USING ERRCODE='P0409'; END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 RETURN NEW;
END $$;
DO $$
DECLARE t text; key text;
BEGIN
 FOR t,key IN SELECT * FROM (VALUES ('customer_invoices','customer_invoice_id'),('customer_transactions','transaction_id'),
 ('customer_payments','payment_id'),('customer_writeoffs','writeoff_id'),('customer_retainers_and_prepayments','retainer_id')) AS x(t,k)
 LOOP
 EXECUTE format('DROP TRIGGER IF EXISTS ds2_sent_record ON %I',t);
 EXECUTE format('CREATE TRIGGER ds2_sent_record BEFORE INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION ds2_guard_sent_record(%L)',t,key);
 END LOOP;
END $$;
CREATE OR REPLACE FUNCTION ds2_guard_sent_owner() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE n text; family integer[];
BEGIN
 PERFORM customer_id FROM customers WHERE account_id=OLD.account_id AND customer_id=OLD.customer_id FOR NO KEY UPDATE;
 IF TG_TABLE_NAME='customers' THEN
   SELECT ds2_locked_invoice('customer_invoices',customer_invoice_id,account_id) INTO n FROM customer_invoices
   WHERE account_id=OLD.account_id AND customer_id=OLD.customer_id AND parent_invoice_id IS NULL
   AND ds2_locked_invoice('customer_invoices',customer_invoice_id,account_id) IS NOT NULL LIMIT 1;
 ELSE
   IF TG_OP='UPDATE' AND NEW.customer_id IS NOT DISTINCT FROM OLD.customer_id AND NEW.account_id=OLD.account_id THEN RETURN NEW; END IF;
   SELECT array_agg(customer_job_id) INTO family FROM customer_jobs WHERE account_id=OLD.account_id
   AND (customer_job_id=COALESCE(OLD.parent_job_id,OLD.customer_job_id) OR parent_job_id=COALESCE(OLD.parent_job_id,OLD.customer_job_id));
   SELECT number INTO n FROM (
      SELECT ds2_locked_invoice('customer_transactions',transaction_id,account_id) AS number FROM customer_transactions WHERE account_id=OLD.account_id AND customer_job_id=ANY(family)
      UNION ALL SELECT ds2_locked_invoice('customer_payments',payment_id,account_id) FROM customer_payments WHERE account_id=OLD.account_id AND customer_job_id=ANY(family)
      UNION ALL SELECT ds2_locked_invoice('customer_writeoffs',writeoff_id,account_id) FROM customer_writeoffs WHERE account_id=OLD.account_id AND customer_job_id=ANY(family)
   ) linked WHERE number IS NOT NULL LIMIT 1;
 END IF;
 IF n IS NOT NULL THEN RAISE EXCEPTION 'locked: part of sent invoice %',n USING ERRCODE='P0409'; END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS ds2_sent_customer ON customers;
CREATE TRIGGER ds2_sent_customer BEFORE DELETE ON customers FOR EACH ROW EXECUTE FUNCTION ds2_guard_sent_owner();
DROP TRIGGER IF EXISTS ds2_sent_job ON customer_jobs;
CREATE TRIGGER ds2_sent_job BEFORE UPDATE OR DELETE ON customer_jobs FOR EACH ROW EXECUTE FUNCTION ds2_guard_sent_owner();
CREATE OR REPLACE FUNCTION ds2_immutable_evidence() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Issued invoice evidence is immutable' USING ERRCODE='P0409'; END $$;
DO $$
DECLARE t text;
BEGIN
 FOREACH t IN ARRAY ARRAY['invoice_issues','invoice_statement_members','invoice_revisions','invoice_history'] LOOP
 EXECUTE format('DROP TRIGGER IF EXISTS ds2_immutable ON %I',t);
 EXECUTE format('CREATE TRIGGER ds2_immutable BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION ds2_immutable_evidence()',t);
 END LOOP;
END $$;
