-- Additive only; no existing business rows are changed. Apply with psql -X -1.
CREATE TABLE IF NOT EXISTS retainer_events (
 event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id integer NOT NULL REFERENCES accounts(account_id),
 customer_id integer NOT NULL REFERENCES customers(customer_id),
 root_retainer_id integer NOT NULL REFERENCES customer_retainers_and_prepayments(retainer_id),
 snapshot_id integer NOT NULL UNIQUE REFERENCES customer_retainers_and_prepayments(retainer_id),
 kind text NOT NULL CHECK(kind IN ('refund','adjustment')),
 direction text NOT NULL CHECK(direction IN ('increase','decrease')),
 amount numeric(10,2) NOT NULL CHECK(amount > 0),
 balance_delta numeric(10,2) NOT NULL CHECK(balance_delta <> 0),
 available_before numeric(10,2) NOT NULL CHECK(available_before >= 0),
 available_after numeric(10,2) NOT NULL CHECK(available_after >= 0),
 event_date date NOT NULL,
 method varchar(50),
 reference varchar(100),
 reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 2000),
 actor_id integer NOT NULL REFERENCES users(user_id),
 created_at timestamp NOT NULL DEFAULT clock_timestamp(),
 CHECK(available_after = available_before - balance_delta),
 CHECK(balance_delta = CASE WHEN direction='increase' THEN -amount ELSE amount END),
 CHECK(kind <> 'refund' OR (direction='decrease' AND length(btrim(method)) > 0 AND method IS NOT NULL AND length(btrim(reference)) > 0 AND reference IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS retainer_events_customer ON retainer_events(account_id,customer_id,created_at,event_id);
CREATE TABLE IF NOT EXISTS duplicate_flags (
 duplicate_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id integer NOT NULL REFERENCES accounts(account_id),
 customer_id integer NOT NULL,
 kind text NOT NULL CHECK(kind IN ('transaction','payment','writeoff','retainer')),
 record_id integer NOT NULL CHECK(record_id > 0),
 canonical_id integer CHECK(canonical_id > 0 AND canonical_id <> record_id),
 reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 2000),
 detected_by integer NOT NULL REFERENCES users(user_id),
 created_at timestamp NOT NULL DEFAULT clock_timestamp(),
 status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','dismissed','removed')),
 resolved_by integer REFERENCES users(user_id),
 resolved_at timestamp,
 resolution_reason text,
 record_snapshot jsonb NOT NULL,
 canonical_snapshot jsonb,
 CHECK((status='open' AND resolved_at IS NULL AND resolved_by IS NULL) OR (status<>'open' AND resolved_at IS NOT NULL AND resolved_by IS NOT NULL AND length(btrim(resolution_reason)) > 0))
);
-- Preserve review evidence when an otherwise empty customer is removed. Ownership
-- is checked under the customer lock by every creating/resolving operation.
ALTER TABLE duplicate_flags DROP CONSTRAINT IF EXISTS duplicate_flags_customer_id_fkey;
CREATE UNIQUE INDEX IF NOT EXISTS duplicate_pair ON duplicate_flags(account_id,kind,LEAST(record_id,COALESCE(canonical_id,record_id)),GREATEST(record_id,COALESCE(canonical_id,record_id)));
CREATE INDEX IF NOT EXISTS duplicate_open_records ON duplicate_flags(account_id,status,kind,record_id);
CREATE TABLE IF NOT EXISTS duplicate_history (
 history_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id integer NOT NULL REFERENCES accounts(account_id),
 duplicate_id integer REFERENCES duplicate_flags(duplicate_id),
 actor_id integer NOT NULL REFERENCES users(user_id),
 action text NOT NULL CHECK(action IN ('flag','scan','dismiss','remove','source_removed')),
 reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 2000),
 before_value jsonb,
 after_value jsonb,
 created_at timestamp NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX IF NOT EXISTS duplicate_history_account ON duplicate_history(account_id,duplicate_id,history_id);
-- Event snapshots are accounting evidence even while pending the next statement.
CREATE OR REPLACE FUNCTION ds2_guard_retainer_event() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF EXISTS(SELECT 1 FROM retainer_events WHERE account_id=OLD.account_id AND snapshot_id=OLD.retainer_id) THEN
   RAISE EXCEPTION 'Retainer event history is immutable; record a new adjustment' USING ERRCODE='P0409';
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS ds2_retainer_event_snapshot ON customer_retainers_and_prepayments;
CREATE TRIGGER ds2_retainer_event_snapshot BEFORE UPDATE OR DELETE ON customer_retainers_and_prepayments FOR EACH ROW EXECUTE FUNCTION ds2_guard_retainer_event();
DO $$
DECLARE t text;
BEGIN
 FOREACH t IN ARRAY ARRAY['retainer_events','duplicate_history'] LOOP
 EXECUTE format('DROP TRIGGER IF EXISTS ds2_immutable ON %I',t);
 EXECUTE format('CREATE TRIGGER ds2_immutable BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION ds2_immutable_evidence()',t);
 END LOOP;
END $$;
-- Explicit membership also freezes the event rendering payload at issuance.
ALTER TABLE invoice_statement_members DROP CONSTRAINT IF EXISTS invoice_statement_members_table_name_check;
ALTER TABLE invoice_statement_members ADD CONSTRAINT invoice_statement_members_table_name_check CHECK(table_name IN ('customer_invoices','customer_transactions','customer_payments','customer_writeoffs','customer_retainers_and_prepayments','retainer_events'));
