-- Business dimension. Legacy financial rows are never rewritten. Apply using psql -X -1.
SELECT set_config('app.audit_source','migration/028.billing_entities',true), set_config('app.audit_reason','Owner-authorized entity schema and explicit legacy attribution',true);
CREATE OR REPLACE FUNCTION ds2_normalize_entity(s text) RETURNS text LANGUAGE sql IMMUTABLE AS $$
 SELECT btrim(regexp_replace(regexp_replace(lower(normalize(COALESCE(s,''),NFKC)),'[[:punct:]]','','g'),'[[:space:]]+',' ','g'))
$$;
CREATE TABLE IF NOT EXISTS billing_entities (
 billing_entity_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id integer NOT NULL REFERENCES accounts(account_id),
 name text NOT NULL CHECK(length(btrim(name)) BETWEEN 1 AND 150),
 legal_name text NOT NULL CHECK(length(btrim(legal_name)) BETWEEN 1 AND 200),
 contact_name text, email text, phone text, address_line1 text, address_line2 text,
 city text, state text, postal_code text, country text NOT NULL DEFAULT 'US',
 logo_key text, logo_sha256 text CHECK(logo_sha256 IS NULL OR logo_sha256 ~ '^[a-f0-9]{64}$'),
 invoice_prefix text NOT NULL CHECK(invoice_prefix ~ '^[A-Z]{1,12}$'),
 active boolean NOT NULL DEFAULT true, is_default boolean NOT NULL DEFAULT false,
 version integer NOT NULL DEFAULT 1 CHECK(version>0),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 CHECK(NOT is_default OR active), UNIQUE(account_id,billing_entity_id), UNIQUE(account_id,invoice_prefix)
);
CREATE UNIQUE INDEX IF NOT EXISTS billing_entity_name_unique ON billing_entities(account_id,ds2_normalize_entity(name));
CREATE UNIQUE INDEX IF NOT EXISTS billing_entity_default_unique ON billing_entities(account_id) WHERE is_default;
CREATE TABLE IF NOT EXISTS billing_entity_aliases (
 alias_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id integer NOT NULL, billing_entity_id integer NOT NULL,
 alias text NOT NULL CHECK(length(btrim(alias)) BETWEEN 1 AND 200),
 normalized_alias text GENERATED ALWAYS AS (ds2_normalize_entity(alias)) STORED,
 source text NOT NULL, reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 2000),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY(account_id,billing_entity_id) REFERENCES billing_entities(account_id,billing_entity_id),
 UNIQUE(account_id,billing_entity_id,normalized_alias)
);
CREATE TABLE IF NOT EXISTS billing_entity_invoice_sequences (
 account_id integer NOT NULL, billing_entity_id integer NOT NULL, year integer NOT NULL CHECK(year BETWEEN 1900 AND 9999),
 last_number integer NOT NULL DEFAULT 0 CHECK(last_number BETWEEN 0 AND 99999),
 PRIMARY KEY(account_id,billing_entity_id,year), FOREIGN KEY(account_id,billing_entity_id) REFERENCES billing_entities(account_id,billing_entity_id)
);
CREATE TABLE IF NOT EXISTS billing_cutovers (
 cutover_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id integer NOT NULL REFERENCES accounts(account_id),
 source text NOT NULL, manifest jsonb NOT NULL, manifest_sha256 text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(), UNIQUE(account_id,source), UNIQUE(account_id,cutover_id)
);
CREATE TABLE IF NOT EXISTS legacy_financial_entity_attributions (
 attribution_id bigserial PRIMARY KEY, account_id integer NOT NULL, customer_id integer,
 table_name text NOT NULL, record_id integer NOT NULL, billing_entity_id integer NOT NULL,
 cutover_id integer NOT NULL, basis text NOT NULL, source_sha256 text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(account_id,table_name,record_id),
 FOREIGN KEY(account_id,billing_entity_id) REFERENCES billing_entities(account_id,billing_entity_id),
 FOREIGN KEY(account_id,cutover_id) REFERENCES billing_cutovers(account_id,cutover_id)
);
CREATE TABLE IF NOT EXISTS billing_entity_reviews (
 review_id bigserial PRIMARY KEY, account_id integer NOT NULL REFERENCES accounts(account_id), customer_id integer,
 table_name text NOT NULL CHECK(table_name IN ('timesheet_entries','customer_transactions')),
 record_id integer NOT NULL, raw_entity text, candidate_ids integer[] NOT NULL DEFAULT '{}',
 source_sha256 text NOT NULL, reason_code text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(), UNIQUE(account_id,table_name,record_id)
);
CREATE TABLE IF NOT EXISTS billing_entity_resolutions (
 resolution_id bigserial PRIMARY KEY, account_id integer NOT NULL, customer_id integer,
 review_id bigint NOT NULL UNIQUE REFERENCES billing_entity_reviews(review_id),
 billing_entity_id integer NOT NULL, reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 2000),
 source_sha256 text NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY(account_id,billing_entity_id) REFERENCES billing_entities(account_id,billing_entity_id)
);
CREATE OR REPLACE FUNCTION ds2_entity_match(aid integer, raw_name text) RETURNS integer[] LANGUAGE sql STABLE SET search_path=public,pg_temp AS $$
 SELECT COALESCE(array_agg(DISTINCT e.billing_entity_id ORDER BY e.billing_entity_id),'{}'::integer[])
 FROM billing_entities e LEFT JOIN billing_entity_aliases a USING(account_id,billing_entity_id)
 WHERE e.account_id=aid AND e.active AND ds2_normalize_entity(raw_name)<>''
 AND ds2_normalize_entity(raw_name) IN(ds2_normalize_entity(e.name),ds2_normalize_entity(e.legal_name),a.normalized_alias)
$$;
-- All new tables are audited BEFORE seeding them.
DO $$ DECLARE spec text; t text; k text; BEGIN
 FOREACH spec IN ARRAY ARRAY['billing_entities:billing_entity_id','billing_entity_aliases:alias_id','billing_entity_invoice_sequences:billing_entity_id',
 'billing_cutovers:cutover_id','legacy_financial_entity_attributions:attribution_id','billing_entity_reviews:review_id','billing_entity_resolutions:resolution_id'] LOOP
 t:=split_part(spec,':',1); k:=split_part(spec,':',2);
 EXECUTE format('DROP TRIGGER IF EXISTS ds2_audit_capture ON %I',t);
 EXECUTE format('CREATE TRIGGER ds2_audit_capture AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION ds2_capture_audit(%L)',t,k);
 EXECUTE format('DROP TRIGGER IF EXISTS ds2_audit_no_truncate ON %I',t);
 EXECUTE format('CREATE TRIGGER ds2_audit_no_truncate BEFORE TRUNCATE ON %I EXECUTE FUNCTION ds2_audit_immutable()',t);
 IF t IN ('billing_cutovers','legacy_financial_entity_attributions','billing_entity_reviews','billing_entity_resolutions') THEN
  EXECUTE format('DROP TRIGGER IF EXISTS ds2_audit_immutable ON %I',t);
  EXECUTE format('CREATE TRIGGER ds2_audit_immutable BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION ds2_audit_immutable()',t);
 END IF;
 END LOOP;
END $$;
INSERT INTO billing_entities(account_id,name,legal_name,invoice_prefix,is_default,logo_key,address_line1,city,state,postal_code,email,phone)
 SELECT a.account_id, CASE WHEN a.account_id=1 THEN 'James F. Kimmel & Associates' ELSE a.account_name END,
 CASE WHEN a.account_id=1 THEN 'James F. Kimmel & Associates' ELSE a.account_name END,'INV',true,a.account_company_logo,
 i.account_street,i.account_city,i.account_state,i.account_zip,i.account_email,i.account_phone
 FROM accounts a LEFT JOIN LATERAL(SELECT * FROM account_information i WHERE i.account_id=a.account_id AND is_account_mailing_address AND is_this_address_active ORDER BY account_info_id DESC LIMIT 1)i ON true
 WHERE NOT EXISTS(SELECT 1 FROM billing_entities e WHERE e.account_id=a.account_id);
INSERT INTO billing_entities(account_id,name,legal_name,invoice_prefix)
 SELECT 1,n,n,p FROM (VALUES ('Kimmel Financial Advisors','KFA'),('Jim Kimmel Insurance Agency, Inc.','JKI'))x(n,p)
 WHERE EXISTS(SELECT 1 FROM accounts WHERE account_id=1)
 ON CONFLICT(account_id,invoice_prefix) DO NOTHING;
INSERT INTO billing_cutovers(account_id,source,manifest,manifest_sha256)
 SELECT account_id,'migration/028/default',jsonb_build_object('default_entity_id',billing_entity_id,'basis','Owner-authorized defaults. Frozen rows unchanged; unknown work held.'),
 encode(sha256(convert_to(jsonb_build_object('default_entity_id',billing_entity_id,'basis','Owner-authorized defaults. Frozen rows unchanged; unknown work held.')::text,'UTF8')),'hex')
 FROM billing_entities WHERE is_default ON CONFLICT(account_id,source) DO NOTHING;
-- Add nullable physical columns; immutable legacy records use the enumerated sidecar.
DO $$ DECLARE spec text; t text; k text; r record; cols text; BEGIN
 FOREACH spec IN ARRAY ARRAY[
 'customer_transactions:transaction_id','customer_payments:payment_id','customer_writeoffs:writeoff_id','customer_retainers_and_prepayments:retainer_id',
 'customer_invoices:customer_invoice_id','retainer_events:event_id','invoice_issues:invoice_id','recurring_customers:recurring_customer_id',
 'customer_quotes:customer_quote_id','customer_jobs:customer_job_id','customer_payments_processed:payment_id',
 'timesheet_entries:timesheet_entry_id','ai_time_tracker_transaction_suggestions:suggestion_id'] LOOP
 t:=split_part(spec,':',1); k:=split_part(spec,':',2);
 EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS billing_entity_id integer',t);
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname=t||'_billing_entity_fk') THEN
 EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY(account_id,billing_entity_id) REFERENCES billing_entities(account_id,billing_entity_id)',t,t||'_billing_entity_fk'); END IF;
 EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I(account_id,billing_entity_id)',t||'_billing_entity_idx',t);
 -- A job may be deliberately shared. Source/review areas may be unresolved.
 IF t NOT IN ('customer_jobs','timesheet_entries','ai_time_tracker_transaction_suggestions') THEN
 EXECUTE format($q$
  INSERT INTO legacy_financial_entity_attributions(account_id,customer_id,table_name,record_id,billing_entity_id,cutover_id,basis,source_sha256)
  SELECT r.account_id,(to_jsonb(r)->>'customer_id')::integer,%L,r.%I,e.billing_entity_id,c.cutover_id,'Legacy default; original record unchanged',
  encode(sha256(convert_to((to_jsonb(r)-'billing_entity_id')::text,'UTF8')),'hex')
  FROM %I r JOIN billing_entities e ON e.account_id=r.account_id AND e.is_default
  JOIN billing_cutovers c ON c.account_id=r.account_id AND c.source='migration/028/default'
  WHERE r.billing_entity_id IS NULL %s ON CONFLICT(account_id,table_name,record_id) DO NOTHING
 $q$,t,k,t,CASE WHEN t='customer_transactions' THEN 'AND r.customer_invoice_id IS NOT NULL' ELSE '' END);
 END IF;
 END LOOP;
END $$;
-- Unissued work: accept exactly one source link and one exact company match.
WITH links AS (
 SELECT t.account_id,t.transaction_id,t.customer_id,count(DISTINCT a.timesheet_entry_id) AS sources,
 min(te.entity) AS raw_entity, min(te.timesheet_entry_id) AS source_id
 FROM customer_transactions t LEFT JOIN ai_category_training_examples a ON a.account_id=t.account_id AND a.transaction_id=t.transaction_id
 LEFT JOIN timesheet_entries te ON te.account_id=t.account_id AND te.timesheet_entry_id=a.timesheet_entry_id
 WHERE t.customer_invoice_id IS NULL AND t.billing_entity_id IS NULL GROUP BY t.account_id,t.transaction_id,t.customer_id
), candidates AS(SELECT *,ds2_entity_match(account_id,raw_entity) AS ids FROM links)
INSERT INTO legacy_financial_entity_attributions(account_id,customer_id,table_name,record_id,billing_entity_id,cutover_id,basis,source_sha256)
 SELECT l.account_id,l.customer_id,'customer_transactions',l.transaction_id,l.ids[1],c.cutover_id,'Verified single tracker source '||l.source_id,
 encode(sha256(convert_to((to_jsonb(t)-'billing_entity_id')::text,'UTF8')),'hex')
 FROM candidates l JOIN customer_transactions t USING(transaction_id,account_id) JOIN billing_cutovers c ON c.account_id=l.account_id AND c.source='migration/028/default'
 WHERE sources=1 AND cardinality(ids)=1 ON CONFLICT(account_id,table_name,record_id) DO NOTHING;
INSERT INTO billing_entity_reviews(account_id,customer_id,table_name,record_id,raw_entity,source_sha256,reason_code)
 SELECT t.account_id,t.customer_id,'customer_transactions',t.transaction_id,NULL,
 encode(sha256(convert_to((to_jsonb(t)-'billing_entity_id')::text,'UTF8')),'hex'),'legacy_source_unresolved'
 FROM customer_transactions t WHERE t.customer_invoice_id IS NULL AND t.billing_entity_id IS NULL
 AND NOT EXISTS(SELECT 1 FROM legacy_financial_entity_attributions a WHERE a.account_id=t.account_id AND a.table_name='customer_transactions' AND a.record_id=t.transaction_id)
 ON CONFLICT(account_id,table_name,record_id) DO NOTHING;
CREATE OR REPLACE FUNCTION ds2_effective_entity(aid integer,t text,rid integer,eid integer) RETURNS integer LANGUAGE sql STABLE SET search_path=public,pg_temp AS $$
 SELECT COALESCE(eid,
 (SELECT a.billing_entity_id FROM legacy_financial_entity_attributions a WHERE a.account_id=aid AND a.table_name=t AND a.record_id=rid),
 (SELECT s.billing_entity_id FROM billing_entity_reviews r JOIN billing_entity_resolutions s USING(review_id,account_id) WHERE r.account_id=aid AND r.table_name=t AND r.record_id=rid))
$$;
-- Read-only entity projection. The application opts in transaction-locally; writes use public.
CREATE SCHEMA IF NOT EXISTS billing_scope;
DO $$ DECLARE spec text; t text; k text; cols text; expr text; BEGIN
 FOREACH spec IN ARRAY ARRAY[
 'customer_transactions:transaction_id','customer_payments:payment_id','customer_writeoffs:writeoff_id','customer_retainers_and_prepayments:retainer_id',
 'customer_invoices:customer_invoice_id','retainer_events:event_id','invoice_issues:invoice_id','recurring_customers:recurring_customer_id',
 'customer_quotes:customer_quote_id','customer_jobs:customer_job_id','customer_payments_processed:payment_id',
 'timesheet_entries:timesheet_entry_id','ai_time_tracker_transaction_suggestions:suggestion_id'] LOOP
 t:=split_part(spec,':',1); k:=split_part(spec,':',2);
 SELECT string_agg('r.'||quote_ident(column_name),', ' ORDER BY ordinal_position) INTO cols FROM information_schema.columns
 WHERE table_schema='public' AND table_name=t AND column_name<>'billing_entity_id';
 expr:=format('public.ds2_effective_entity(r.account_id,%L,r.%I,r.billing_entity_id)',t,k);
 EXECUTE format('CREATE OR REPLACE VIEW billing_scope.%I AS SELECT %s,%s AS billing_entity_id FROM public.%I r WHERE NULLIF(current_setting(''app.billing_entity_id'',true),'''') IS NULL OR %s=NULLIF(current_setting(''app.billing_entity_id'',true),'''')::integer %s',t,cols,expr,t,expr,CASE WHEN t='customer_jobs' THEN 'OR r.billing_entity_id IS NULL' ELSE '' END);
 END LOOP;
END $$;
