-- H4. Existing plans keep their legacy settings and receive an explicit, audited
-- first automated period. No charge is generated by this migration.
SELECT set_config('app.audit_source','migration/043.recurring_billing',true),
       set_config('app.audit_reason','Recurring cutover: exclude previously manually billed periods',true),
       set_config('ds2.reason','Recurring cutover: exclude previously manually billed periods',true);
ALTER TABLE recurring_customers ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE recurring_customers ADD COLUMN IF NOT EXISTS job_id integer REFERENCES customer_jobs(customer_job_id);
ALTER TABLE recurring_customers ADD COLUMN IF NOT EXISTS anchor_start_date date;
ALTER TABLE recurring_customers ADD COLUMN IF NOT EXISTS first_automated_period date;
ALTER TABLE recurring_customers ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE recurring_customers ADD COLUMN IF NOT EXISTS review_status text NOT NULL DEFAULT 'ready';
ALTER TABLE recurring_customers ADD COLUMN IF NOT EXISTS cutover_date date;
CREATE TABLE IF NOT EXISTS recurring_plan_cutovers (
 cutover_id bigserial PRIMARY KEY, account_id integer NOT NULL, customer_id integer NOT NULL,
 billing_entity_id integer NOT NULL, plan_id integer NOT NULL UNIQUE REFERENCES recurring_customers(recurring_customer_id),
 rollout_date date NOT NULL, original jsonb NOT NULL, reason text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY(account_id,billing_entity_id) REFERENCES billing_entities(account_id,billing_entity_id)
);
CREATE TABLE IF NOT EXISTS recurring_charge_occurrences (
 occurrence_id serial PRIMARY KEY, account_id integer NOT NULL, customer_id integer NOT NULL,
 billing_entity_id integer NOT NULL, plan_id integer NOT NULL REFERENCES recurring_customers(recurring_customer_id),
 period_start date NOT NULL, period_end date NOT NULL, due_date date NOT NULL,
 snapshot_amount numeric(10,2) NOT NULL CHECK(snapshot_amount>0), snapshot_description text NOT NULL,
 plan_version integer NOT NULL, transaction_id integer UNIQUE REFERENCES customer_transactions(transaction_id),
 state text NOT NULL CHECK(state IN ('generated','skipped','issued')), version integer NOT NULL DEFAULT 1,
 reason text NOT NULL, source text NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(plan_id,period_start), UNIQUE(account_id,customer_id,billing_entity_id,occurrence_id),
 CHECK(period_start<=due_date AND due_date<=period_end),
 FOREIGN KEY(account_id,billing_entity_id) REFERENCES billing_entities(account_id,billing_entity_id)
);
CREATE TABLE IF NOT EXISTS recurring_occurrence_events (
 event_id serial PRIMARY KEY, account_id integer NOT NULL, customer_id integer NOT NULL, billing_entity_id integer NOT NULL,
 occurrence_id integer NOT NULL, kind text NOT NULL CHECK(kind IN ('generated','edited','skipped','issued')),
 reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 2000), detail jsonb NOT NULL,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY(account_id,customer_id,billing_entity_id,occurrence_id) REFERENCES recurring_charge_occurrences(account_id,customer_id,billing_entity_id,occurrence_id)
);
DO $$ DECLARE spec text;t text;k text; BEGIN
 FOREACH spec IN ARRAY ARRAY['recurring_plan_cutovers:cutover_id','recurring_charge_occurrences:occurrence_id','recurring_occurrence_events:event_id'] LOOP
  t:=split_part(spec,':',1);k:=split_part(spec,':',2);
  EXECUTE format('DROP TRIGGER IF EXISTS ds2_audit_capture ON %I',t);
  EXECUTE format('CREATE TRIGGER ds2_audit_capture AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION ds2_capture_audit(%L)',t,k);
  EXECUTE format('DROP TRIGGER IF EXISTS ds2_audit_no_truncate ON %I',t);
  EXECUTE format('CREATE TRIGGER ds2_audit_no_truncate BEFORE TRUNCATE ON %I FOR EACH STATEMENT EXECUTE FUNCTION ds2_audit_immutable()',t);
  EXECUTE format('DROP TRIGGER IF EXISTS ds2_ar_scope_guard ON %I',t);
  EXECUTE format('CREATE TRIGGER ds2_ar_scope_guard BEFORE INSERT OR UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION ds2_ar_scope_guard()',t);
  EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I(account_id,customer_id,billing_entity_id)',t||'_scope',t);
  IF t<>'recurring_charge_occurrences' THEN
   EXECUTE format('DROP TRIGGER IF EXISTS ds2_audit_immutable ON %I',t);
   EXECUTE format('CREATE TRIGGER ds2_audit_immutable BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION ds2_audit_immutable()',t);
  END IF;
 END LOOP;
END $$;
-- Default-business routing follows H2, never the reporting tracker attribution.
INSERT INTO recurring_plan_cutovers(account_id,customer_id,billing_entity_id,plan_id,rollout_date,original,reason)
SELECT r.account_id,r.customer_id,e.billing_entity_id,r.recurring_customer_id,
 (clock_timestamp() AT TIME ZONE 'America/Phoenix')::date,to_jsonb(r),
 'Owner cutover default: first automated due date on or after rollout; earlier periods excluded to avoid billing twice'
FROM recurring_customers r JOIN billing_entities e ON e.account_id=r.account_id AND e.is_default
WHERE r.anchor_start_date IS NULL AND r.customer_id IS NOT NULL
ON CONFLICT(plan_id) DO NOTHING;
UPDATE recurring_customers r SET billing_entity_id=c.billing_entity_id,
 description=COALESCE(NULLIF(btrim(r.description),''),'Recurring services'),anchor_start_date=r.start_date,cutover_date=c.rollout_date,
 review_status=CASE WHEN lower(r.subscription_frequency) IN ('monthly','quarterly','semiannual','annual') AND r.bill_on_date BETWEEN 1 AND 31 AND r.recurring_bill_amount>0 AND (r.end_date IS NULL OR r.end_date>=r.start_date) THEN 'ready' ELSE 'needs_review' END,
 first_automated_period=(SELECT d::date FROM generate_series(date_trunc('month',r.start_date)::date,
 (c.rollout_date+interval '13 months')::date,
 CASE lower(r.subscription_frequency) WHEN 'quarterly' THEN interval '3 months' WHEN 'semiannual' THEN interval '6 months' WHEN 'annual' THEN interval '12 months' ELSE interval '1 month' END) d
 WHERE d::date+LEAST(GREATEST(r.bill_on_date,1),extract(day FROM d+interval '1 month - 1 day')::integer)-1>=GREATEST(c.rollout_date,r.start_date) ORDER BY d LIMIT 1)
FROM recurring_plan_cutovers c WHERE c.plan_id=r.recurring_customer_id AND r.anchor_start_date IS NULL;
-- Charges have no staff time or work-description catalog dependency.
ALTER TABLE customer_transactions ALTER COLUMN logged_for_user_id DROP NOT NULL;
ALTER TABLE customer_transactions ALTER COLUMN general_work_description_id DROP NOT NULL;
CREATE OR REPLACE FUNCTION ds2_recurring_occurrence_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE p recurring_customers;t customer_transactions; BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Recurring periods cannot be deleted; skip with a reason' USING ERRCODE='P0409';END IF;
 SELECT * INTO p FROM public.recurring_customers WHERE recurring_customer_id=NEW.plan_id;
 IF p.account_id<>NEW.account_id OR p.customer_id<>NEW.customer_id OR p.billing_entity_id<>NEW.billing_entity_id THEN RAISE EXCEPTION 'Recurring plan scope mismatch' USING ERRCODE='P0409';END IF;
 IF TG_OP='UPDATE' AND (OLD.state<>'generated' OR (to_jsonb(NEW)-ARRAY['state','version']) IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['state','version'])) THEN
  RAISE EXCEPTION 'Recurring occurrence identity and issued or skipped periods are locked' USING ERRCODE='P0409';END IF;
 IF TG_OP='UPDATE' AND COALESCE(current_setting('app.recurring_write',true),'')<>'on' THEN RAISE EXCEPTION 'Use recurring charge actions' USING ERRCODE='P0409';END IF;
 IF NEW.transaction_id IS NOT NULL THEN
  SELECT * INTO t FROM public.customer_transactions WHERE transaction_id=NEW.transaction_id;
  IF t.account_id<>NEW.account_id OR t.customer_id<>NEW.customer_id OR t.billing_entity_id<>NEW.billing_entity_id OR t.transaction_type<>'Charge' OR t.is_excess_to_subscription OR t.quantity<>1 THEN RAISE EXCEPTION 'Recurring charge scope mismatch' USING ERRCODE='P0409';END IF;
 END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS ds2_recurring_guard ON recurring_charge_occurrences;
CREATE TRIGGER ds2_recurring_guard BEFORE INSERT OR UPDATE OR DELETE ON recurring_charge_occurrences FOR EACH ROW EXECUTE FUNCTION ds2_recurring_occurrence_guard();
CREATE OR REPLACE FUNCTION ds2_recurring_transaction_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE o recurring_charge_occurrences; BEGIN
 SELECT * INTO o FROM public.recurring_charge_occurrences WHERE transaction_id=OLD.transaction_id;
 IF FOUND THEN
  IF TG_OP='DELETE' OR o.state<>'generated' OR
   ((to_jsonb(NEW)-'customer_invoice_id') IS DISTINCT FROM (to_jsonb(OLD)-'customer_invoice_id') AND COALESCE(current_setting('app.recurring_write',true),'')<>'on') THEN
   RAISE EXCEPTION 'Use recurring charge edit or skip before finalize; issued charges are locked' USING ERRCODE='P0409';
  END IF;
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD;END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS ds2_recurring_guard ON customer_transactions;
CREATE TRIGGER ds2_recurring_guard BEFORE UPDATE OR DELETE ON customer_transactions FOR EACH ROW EXECUTE FUNCTION ds2_recurring_transaction_guard();
CREATE OR REPLACE FUNCTION ds2_recurring_staff_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF (NEW.logged_for_user_id IS NULL OR NEW.general_work_description_id IS NULL) AND NOT EXISTS(
 SELECT 1 FROM public.recurring_charge_occurrences o WHERE o.transaction_id=NEW.transaction_id AND o.account_id=NEW.account_id AND o.customer_id=NEW.customer_id)
 THEN RAISE EXCEPTION 'Only a recurring fee may omit staff or a work catalog selection' USING ERRCODE='P0409';END IF;
 RETURN NULL;
END $$;
DROP TRIGGER IF EXISTS ds2_recurring_staff_guard ON customer_transactions;
CREATE CONSTRAINT TRIGGER ds2_recurring_staff_guard AFTER INSERT OR UPDATE ON customer_transactions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION ds2_recurring_staff_guard();
CREATE OR REPLACE FUNCTION ds2_recurring_plan_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='UPDATE' AND EXISTS(SELECT 1 FROM public.recurring_charge_occurrences WHERE plan_id=OLD.recurring_customer_id) AND
 (NEW.account_id,NEW.customer_id,NEW.billing_entity_id,NEW.start_date,NEW.anchor_start_date,lower(NEW.subscription_frequency),NEW.bill_on_date,NEW.first_automated_period)
 IS DISTINCT FROM (OLD.account_id,OLD.customer_id,OLD.billing_entity_id,OLD.start_date,OLD.anchor_start_date,lower(OLD.subscription_frequency),OLD.bill_on_date,OLD.first_automated_period)
 THEN RAISE EXCEPTION 'A generated plan keeps its client, business and calendar; end it and create a new plan' USING ERRCODE='P0409';END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS ds2_recurring_plan_guard ON recurring_customers;
CREATE TRIGGER ds2_recurring_plan_guard BEFORE UPDATE ON recurring_customers FOR EACH ROW EXECUTE FUNCTION ds2_recurring_plan_guard();
-- Append newly added plan columns to the entity projection without moving its
-- existing column positions (CREATE OR REPLACE VIEW compatibility).
DO $$ DECLARE cols text; BEGIN
 SELECT string_agg(CASE WHEN column_name='billing_entity_id' THEN 'public.ds2_effective_entity(r.account_id,''recurring_customers'',r.recurring_customer_id,r.billing_entity_id) AS billing_entity_id' ELSE 'r.'||quote_ident(column_name) END,',' ORDER BY ordinal_position) INTO cols
 FROM information_schema.columns WHERE table_schema='public' AND table_name='recurring_customers';
 EXECUTE 'CREATE OR REPLACE VIEW billing_scope.recurring_customers AS SELECT '||cols||' FROM public.recurring_customers r WHERE NULLIF(current_setting(''app.billing_entity_id'',true),'''') IS NULL OR public.ds2_effective_entity(r.account_id,''recurring_customers'',r.recurring_customer_id,r.billing_entity_id)=NULLIF(current_setting(''app.billing_entity_id'',true),'''')::integer';
END $$;
ALTER TABLE invoice_statement_members DROP CONSTRAINT IF EXISTS invoice_statement_members_table_name_check;
ALTER TABLE invoice_statement_members ADD CONSTRAINT invoice_statement_members_table_name_check CHECK(table_name IN(
 'customer_invoices','customer_transactions','customer_payments','customer_writeoffs','customer_retainers_and_prepayments','retainer_events',
 'ar_obligations','payment_receipts','ar_applications','client_credit_lots','client_credit_events','receipt_events',
 'credit_memos','credit_memo_lines','credit_memo_reversals','invoice_voids','rebill_links','client_refunds','correction_postings',
 'recurring_charge_occurrences','recurring_occurrence_events'));
