--
-- PostgreSQL database dump
--

\restrict d9d5rZWKjvzrOomSviqSxExRjo63CZnraaJBSLbJC1CcB45LT28Sf38rqONR8hq

-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 17.9 (Postgres.app)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: dblink; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS dblink WITH SCHEMA public;


--
-- Name: EXTENSION dblink; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION dblink IS 'connect to other PostgreSQL databases from within a database';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_audits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_audits (
    audit_id bigint NOT NULL,
    account_id integer NOT NULL,
    customer_id integer NOT NULL,
    run_by_user_id integer,
    run_by_display_name character varying(100) NOT NULL,
    status character varying(20) DEFAULT 'completed'::character varying NOT NULL,
    total_invoiced numeric(12,2) DEFAULT 0 NOT NULL,
    total_paid numeric(12,2) DEFAULT 0 NOT NULL,
    total_transactions numeric(12,2) DEFAULT 0 NOT NULL,
    total_writeoffs numeric(12,2) DEFAULT 0 NOT NULL,
    outstanding_invoices numeric(12,2) DEFAULT 0 NOT NULL,
    unbilled_billable numeric(12,2) DEFAULT 0 NOT NULL,
    unbilled_payments numeric(12,2) DEFAULT 0 NOT NULL,
    unbilled_writeoffs numeric(12,2) DEFAULT 0 NOT NULL,
    audit_balance numeric(12,2) DEFAULT 0 NOT NULL,
    strict_ledger_balance numeric(12,2) DEFAULT 0 NOT NULL,
    discrepancy_count integer DEFAULT 0 NOT NULL,
    discrepancies jsonb DEFAULT '[]'::jsonb NOT NULL,
    ledger jsonb DEFAULT '[]'::jsonb NOT NULL,
    summary jsonb DEFAULT '{}'::jsonb NOT NULL,
    notes text,
    error_message text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    narrative text,
    narrative_findings jsonb,
    narrative_actions jsonb,
    narrative_model character varying(120),
    narrative_cost_usd numeric(10,6),
    narrative_request_id character varying(64),
    pdf_s3_key text,
    pdf_generated_at timestamp without time zone,
    app_invoice_total numeric(12,2),
    app_balance_error text
);


--
-- Name: account_audits_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account_audits ALTER COLUMN audit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_audits_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_automation_recipients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_automation_recipients (
    account_automation_recipient_id integer NOT NULL,
    account_id integer NOT NULL,
    automation_key character varying(100) NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


--
-- Name: account_automation_recipients_account_automation_recipient__seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account_automation_recipients ALTER COLUMN account_automation_recipient_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_automation_recipients_account_automation_recipient__seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_automation_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_automation_settings (
    account_automation_setting_id integer NOT NULL,
    account_id integer NOT NULL,
    automation_key character varying(100) NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


--
-- Name: account_automation_settings_account_automation_setting_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account_automation_settings ALTER COLUMN account_automation_setting_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_automation_settings_account_automation_setting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_information; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_information (
    account_info_id integer NOT NULL,
    account_id integer NOT NULL,
    account_street character varying(255),
    account_city character varying(100),
    account_state character varying(2),
    account_zip character varying(10),
    account_email character varying(255),
    account_phone character varying(20),
    is_this_address_active boolean NOT NULL,
    is_account_physical_address boolean NOT NULL,
    is_account_billing_address boolean NOT NULL,
    is_account_mailing_address boolean NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: account_information_account_info_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account_information ALTER COLUMN account_info_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_information_account_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    account_id integer NOT NULL,
    account_name character varying(100) NOT NULL,
    account_type character varying(50) NOT NULL,
    is_account_active boolean NOT NULL,
    account_statement character varying(255),
    account_interest_statement character varying(255),
    account_invoice_interest_rate numeric(10,2),
    account_invoice_template_option character varying(100),
    created_at timestamp without time zone DEFAULT now(),
    account_company_logo character varying(255),
    ai_daily_cost_cap_usd numeric(8,2)
);


--
-- Name: accounts_account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_call_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_call_log (
    ai_call_log_id bigint NOT NULL,
    request_id character varying(64) NOT NULL,
    account_id integer NOT NULL,
    user_id integer,
    timesheet_entry_id integer,
    provider character varying(30) DEFAULT 'bedrock'::character varying NOT NULL,
    feature character varying(60) NOT NULL,
    model_id character varying(120) NOT NULL,
    input_tokens integer,
    output_tokens integer,
    cost_usd numeric(10,6),
    latency_ms integer,
    status character varying(20) DEFAULT 'ok'::character varying NOT NULL,
    error_message text,
    s3_log_key text,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: ai_call_log_ai_call_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_call_log ALTER COLUMN ai_call_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_call_log_ai_call_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_category_training_examples; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_category_training_examples (
    training_id integer NOT NULL,
    account_id integer NOT NULL,
    timesheet_entry_id integer,
    transaction_id integer,
    original_category text,
    suggested_category text,
    final_category text NOT NULL,
    ai_reason text,
    ai_confidence numeric(5,4),
    ai_source character varying(30) DEFAULT 'ai'::character varying,
    original_notes text,
    sanitized_notes text,
    duration_minutes integer,
    entity text,
    uploaded_to_vector_store boolean DEFAULT false NOT NULL,
    uploaded_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: ai_category_training_examples_training_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_category_training_examples ALTER COLUMN training_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_category_training_examples_training_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_reviewer_corrections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_reviewer_corrections (
    correction_id integer NOT NULL,
    account_id integer NOT NULL,
    transaction_id integer,
    timesheet_entry_id integer,
    reviewer_user_id integer,
    field_name character varying(64) NOT NULL,
    original_value text,
    final_value text,
    original_label text,
    final_label text,
    sanitized_notes text,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: ai_reviewer_corrections_correction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_reviewer_corrections ALTER COLUMN correction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_reviewer_corrections_correction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_time_tracker_transaction_suggestions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_time_tracker_transaction_suggestions (
    suggestion_id integer NOT NULL,
    account_id integer NOT NULL,
    timesheet_entry_id integer NOT NULL,
    sanitized_notes text NOT NULL,
    suggested_category text,
    suggested_job_category_id integer,
    suggested_job_type_id integer,
    suggested_general_work_description_id integer,
    suggested_entity text,
    suggested_customer_id integer,
    suggested_customer_display_name text,
    ai_confidence numeric(5,4),
    ai_reason text,
    ai_payload jsonb,
    status character varying(30) DEFAULT 'pending'::character varying NOT NULL,
    source character varying(30) DEFAULT 'ai'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: ai_time_tracker_transaction_suggestions_suggestion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_time_tracker_transaction_suggestions ALTER COLUMN suggestion_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_time_tracker_transaction_suggestions_suggestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_general_work_descriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_general_work_descriptions (
    general_work_description_id integer NOT NULL,
    account_id integer NOT NULL,
    general_work_description character varying(255) NOT NULL,
    estimated_time integer NOT NULL,
    is_general_work_description_active boolean NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    created_by_user_id integer NOT NULL
);


--
-- Name: customer_general_work_descripti_general_work_description_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_general_work_descriptions ALTER COLUMN general_work_description_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_general_work_descripti_general_work_description_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_information; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_information (
    customer_info_id integer NOT NULL,
    account_id integer NOT NULL,
    customer_id integer NOT NULL,
    customer_street character varying(255),
    customer_city character varying(100),
    customer_state character varying(2),
    customer_zip character varying(10),
    customer_email character varying(255),
    customer_phone character varying(20),
    is_this_address_active boolean NOT NULL,
    is_customer_physical_address boolean NOT NULL,
    is_customer_billing_address boolean NOT NULL,
    is_customer_mailing_address boolean NOT NULL,
    created_by_user_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: customer_information_customer_info_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_information ALTER COLUMN customer_info_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_information_customer_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_invoices (
    customer_invoice_id integer NOT NULL,
    parent_invoice_id integer,
    account_id integer NOT NULL,
    customer_id integer NOT NULL,
    customer_info_id integer NOT NULL,
    invoice_number character varying(100),
    invoice_date date NOT NULL,
    due_date date NOT NULL,
    beginning_balance numeric(10,2) NOT NULL,
    total_payments numeric(10,2) NOT NULL,
    total_charges numeric(10,2) NOT NULL,
    total_write_offs numeric(10,2) NOT NULL,
    total_retainers numeric(10,2) NOT NULL,
    total_amount_due numeric(10,2) NOT NULL,
    remaining_balance_on_invoice numeric(10,2),
    is_invoice_paid_in_full boolean NOT NULL,
    fully_paid_date date,
    created_at timestamp without time zone DEFAULT now(),
    created_by_user_id integer NOT NULL,
    start_date date,
    end_date date,
    invoice_file_location character varying(255),
    notes text
);


--
-- Name: customer_invoices_customer_invoice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_invoices ALTER COLUMN customer_invoice_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_invoices_customer_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_job_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_job_categories (
    customer_job_category_id integer NOT NULL,
    account_id integer NOT NULL,
    customer_job_category character varying,
    is_job_category_active boolean NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    created_by_user_id integer NOT NULL
);


--
-- Name: customer_job_categories_customer_job_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_job_categories ALTER COLUMN customer_job_category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_job_categories_customer_job_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_job_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_job_types (
    job_type_id integer NOT NULL,
    account_id integer NOT NULL,
    customer_job_category_id integer,
    job_description character varying NOT NULL,
    book_rate integer,
    estimated_straight_time integer,
    is_job_type_active boolean NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    created_by_user_id integer NOT NULL
);


--
-- Name: customer_job_types_job_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_job_types ALTER COLUMN job_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_job_types_job_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_jobs (
    customer_job_id integer NOT NULL,
    parent_job_id integer,
    account_id integer NOT NULL,
    customer_id integer,
    job_type_id integer NOT NULL,
    job_quote_amount numeric(10,2),
    agreed_job_amount numeric(10,2),
    current_job_total numeric(10,2),
    job_status numeric(10,2),
    is_job_complete boolean,
    is_quote boolean NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    created_by_user_id integer NOT NULL,
    notes text
);


--
-- Name: customer_jobs_customer_job_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_jobs ALTER COLUMN customer_job_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_jobs_customer_job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_payments (
    payment_id integer NOT NULL,
    customer_id integer NOT NULL,
    account_id integer NOT NULL,
    customer_job_id integer,
    retainer_id integer,
    customer_invoice_id integer,
    payment_date date NOT NULL,
    payment_amount numeric(10,2) NOT NULL,
    form_of_payment character varying(50),
    payment_reference_number character varying(50),
    is_transaction_billable boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    created_by_user_id integer NOT NULL,
    note text
);


--
-- Name: customer_payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_payments ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_payments_processed; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_payments_processed (
    payment_id integer NOT NULL,
    account_id integer NOT NULL,
    customer_id integer,
    matched_customer_id integer,
    customer_name text DEFAULT ''::text NOT NULL,
    matched_customer_name text DEFAULT ''::text NOT NULL,
    customer_invoice_id text DEFAULT ''::text NOT NULL,
    customer_job_id text DEFAULT ''::text NOT NULL,
    retainer_id text DEFAULT ''::text NOT NULL,
    payment_amount numeric(12,2),
    payment_reference_number text DEFAULT ''::text NOT NULL,
    payment_date date,
    form_of_payment character varying(30) DEFAULT ''::character varying NOT NULL,
    is_transaction_billable boolean DEFAULT true NOT NULL,
    is_payment_processed boolean DEFAULT false NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    date_processed timestamp without time zone,
    note text DEFAULT ''::text NOT NULL,
    source_file text DEFAULT ''::text NOT NULL,
    file_location text DEFAULT ''::text NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    created_by_user_id integer DEFAULT 1 NOT NULL
);


--
-- Name: customer_payments_processed_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_payments_processed ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_payments_processed_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_quotes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_quotes (
    customer_quote_id integer NOT NULL,
    account_id integer NOT NULL,
    customer_id integer NOT NULL,
    customer_job_id integer,
    amount_quoted numeric(10,2) NOT NULL,
    is_quote_active boolean NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    created_by_user_id integer NOT NULL,
    notes text
);


--
-- Name: customer_quotes_customer_quote_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_quotes ALTER COLUMN customer_quote_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_quotes_customer_quote_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_rate_agreements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_rate_agreements (
    rate_agreement_id integer NOT NULL,
    account_id integer NOT NULL,
    customer_id integer NOT NULL,
    agreement_year integer NOT NULL,
    agreed_rate numeric(10,2) NOT NULL,
    notes text,
    created_at timestamp without time zone DEFAULT now(),
    created_by_user_id integer NOT NULL
);


--
-- Name: customer_rate_agreements_rate_agreement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_rate_agreements ALTER COLUMN rate_agreement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_rate_agreements_rate_agreement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_retainers_and_prepayments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_retainers_and_prepayments (
    retainer_id integer NOT NULL,
    parent_retainer_id integer,
    customer_id integer NOT NULL,
    account_id integer NOT NULL,
    display_name character varying(100),
    type_of_hold character varying(50) NOT NULL,
    starting_amount numeric(10,2) NOT NULL,
    current_amount numeric(10,2) NOT NULL,
    form_of_payment character varying(50),
    payment_reference_number character varying(50),
    is_retainer_active boolean NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    created_by_user_id integer NOT NULL,
    note text
);


--
-- Name: customer_retainers_and_prepayments_retainer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_retainers_and_prepayments ALTER COLUMN retainer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_retainers_and_prepayments_retainer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_transactions (
    transaction_id integer NOT NULL,
    account_id integer NOT NULL,
    customer_id integer NOT NULL,
    customer_job_id integer,
    retainer_id integer,
    customer_invoice_id integer,
    logged_for_user_id integer NOT NULL,
    general_work_description_id integer NOT NULL,
    detailed_work_description text,
    transaction_date date NOT NULL,
    transaction_type character varying(50) NOT NULL,
    quantity numeric(10,2) DEFAULT 1 NOT NULL,
    unit_cost numeric(10,2) NOT NULL,
    total_transaction numeric(10,2) NOT NULL,
    is_transaction_billable boolean NOT NULL,
    is_excess_to_subscription boolean NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    created_by_user_id integer NOT NULL,
    note text
);


--
-- Name: customer_transactions_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_transactions ALTER COLUMN transaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_transactions_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_writeoffs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_writeoffs (
    writeoff_id integer NOT NULL,
    customer_id integer NOT NULL,
    account_id integer NOT NULL,
    customer_invoice_id integer,
    customer_job_id integer,
    writeoff_date date NOT NULL,
    writeoff_amount numeric(10,2) NOT NULL,
    transaction_type character varying(50) NOT NULL,
    writeoff_reason character varying(50) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    created_by_user_id integer NOT NULL,
    note text
);


--
-- Name: customer_writeoffs_writeoff_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_writeoffs ALTER COLUMN writeoff_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_writeoffs_writeoff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customers (
    customer_id integer NOT NULL,
    account_id integer NOT NULL,
    business_name character varying(100),
    customer_name character varying(100) NOT NULL,
    display_name character varying(100) NOT NULL,
    is_commercial_customer boolean NOT NULL,
    is_customer_active boolean NOT NULL,
    is_billable boolean NOT NULL,
    is_recurring boolean NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: customers_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customers ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invalid_timesheets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invalid_timesheets (
    invalid_timesheet_error_id integer NOT NULL,
    account_id integer NOT NULL,
    timesheet_name text NOT NULL,
    error_message text,
    is_resolved boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    notes text
);


--
-- Name: invalid_timesheets_invalid_timesheet_error_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.invalid_timesheets ALTER COLUMN invalid_timesheet_error_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invalid_timesheets_invalid_timesheet_error_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    notification_id integer NOT NULL,
    account_id integer NOT NULL,
    user_id integer NOT NULL,
    type character varying(60) NOT NULL,
    title character varying(200) NOT NULL,
    body text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    read_at timestamp without time zone,
    expires_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recurring_customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recurring_customers (
    recurring_customer_id integer NOT NULL,
    account_id integer NOT NULL,
    customer_id integer,
    subscription_frequency character varying(255) NOT NULL,
    bill_on_date integer NOT NULL,
    recurring_bill_amount numeric(10,2) NOT NULL,
    start_date date NOT NULL,
    end_date date,
    is_recurring_customer_active boolean NOT NULL,
    created_by_user_id integer NOT NULL
);


--
-- Name: recurring_customers_recurring_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recurring_customers ALTER COLUMN recurring_customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurring_customers_recurring_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: template_downloads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.template_downloads (
    template_download_id bigint NOT NULL,
    account_id integer NOT NULL,
    user_id integer NOT NULL,
    customer_count integer NOT NULL,
    employee_count integer NOT NULL,
    category_count integer NOT NULL,
    downloaded_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: template_downloads_template_download_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.template_downloads ALTER COLUMN template_download_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.template_downloads_template_download_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: time_tracker_staff; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.time_tracker_staff (
    id integer NOT NULL,
    user_id integer NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: time_tracker_staff_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.time_tracker_staff ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.time_tracker_staff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: timesheet_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.timesheet_entries (
    timesheet_entry_id integer NOT NULL,
    account_id integer NOT NULL,
    user_id integer NOT NULL,
    employee_name text,
    timesheet_name text NOT NULL,
    time_tracker_start_date date NOT NULL,
    time_tracker_end_date date NOT NULL,
    date date NOT NULL,
    entity text,
    category text,
    company_name text,
    first_name text,
    last_name text,
    duration integer NOT NULL,
    notes text NOT NULL,
    is_processed boolean DEFAULT false,
    is_deleted boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    hold_reason text,
    ai_attempted_at timestamp without time zone,
    ai_payload jsonb,
    suggested_customer_id integer,
    matched_user_id integer
);


--
-- Name: timesheet_entries_timesheet_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.timesheet_entries ALTER COLUMN timesheet_entry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timesheet_entries_timesheet_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: timesheet_errors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.timesheet_errors (
    timesheet_error_id integer NOT NULL,
    account_id integer NOT NULL,
    user_id integer NOT NULL,
    timesheet_name text NOT NULL,
    time_tracker_start_date date NOT NULL,
    time_tracker_end_date date NOT NULL,
    error_message jsonb NOT NULL,
    is_resolved boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    notes text
);


--
-- Name: timesheet_errors_timesheet_error_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.timesheet_errors ALTER COLUMN timesheet_error_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timesheet_errors_timesheet_error_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_login_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_login_log (
    user_login_log_id integer NOT NULL,
    user_id integer NOT NULL,
    account_id integer NOT NULL,
    login_ip character varying(50),
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: user_login_log_user_login_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_login_log ALTER COLUMN user_login_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_login_log_user_login_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    account_id integer NOT NULL,
    email character varying(255) NOT NULL,
    display_name character varying(100) NOT NULL,
    cost_rate numeric(10,2),
    billing_rate numeric(10,2),
    job_title character varying(50) NOT NULL,
    access_level character varying(50) NOT NULL,
    is_user_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_audits account_audits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_audits
    ADD CONSTRAINT account_audits_pkey PRIMARY KEY (audit_id);


--
-- Name: account_automation_recipients account_automation_recipients_account_id_automation_key_use_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_automation_recipients
    ADD CONSTRAINT account_automation_recipients_account_id_automation_key_use_key UNIQUE (account_id, automation_key, user_id);


--
-- Name: account_automation_recipients account_automation_recipients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_automation_recipients
    ADD CONSTRAINT account_automation_recipients_pkey PRIMARY KEY (account_automation_recipient_id);


--
-- Name: account_automation_settings account_automation_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_automation_settings
    ADD CONSTRAINT account_automation_settings_pkey PRIMARY KEY (account_automation_setting_id);


--
-- Name: account_automation_settings account_automation_settings_unique_account_automation; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_automation_settings
    ADD CONSTRAINT account_automation_settings_unique_account_automation UNIQUE (account_id, automation_key);


--
-- Name: account_information account_information_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_information
    ADD CONSTRAINT account_information_pkey PRIMARY KEY (account_info_id);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (account_id);


--
-- Name: ai_call_log ai_call_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_call_log
    ADD CONSTRAINT ai_call_log_pkey PRIMARY KEY (ai_call_log_id);


--
-- Name: ai_category_training_examples ai_category_training_examples_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_category_training_examples
    ADD CONSTRAINT ai_category_training_examples_pkey PRIMARY KEY (training_id);


--
-- Name: ai_reviewer_corrections ai_reviewer_corrections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_reviewer_corrections
    ADD CONSTRAINT ai_reviewer_corrections_pkey PRIMARY KEY (correction_id);


--
-- Name: ai_time_tracker_transaction_suggestions ai_time_tracker_transaction_suggestions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_time_tracker_transaction_suggestions
    ADD CONSTRAINT ai_time_tracker_transaction_suggestions_pkey PRIMARY KEY (suggestion_id);


--
-- Name: customer_general_work_descriptions customer_general_work_descriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_general_work_descriptions
    ADD CONSTRAINT customer_general_work_descriptions_pkey PRIMARY KEY (general_work_description_id);


--
-- Name: customer_information customer_information_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_information
    ADD CONSTRAINT customer_information_pkey PRIMARY KEY (customer_info_id);


--
-- Name: customer_invoices customer_invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_invoices
    ADD CONSTRAINT customer_invoices_pkey PRIMARY KEY (customer_invoice_id);


--
-- Name: customer_job_categories customer_job_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_job_categories
    ADD CONSTRAINT customer_job_categories_pkey PRIMARY KEY (customer_job_category_id);


--
-- Name: customer_job_types customer_job_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_job_types
    ADD CONSTRAINT customer_job_types_pkey PRIMARY KEY (job_type_id);


--
-- Name: customer_jobs customer_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_jobs
    ADD CONSTRAINT customer_jobs_pkey PRIMARY KEY (customer_job_id);


--
-- Name: customer_payments customer_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_payments
    ADD CONSTRAINT customer_payments_pkey PRIMARY KEY (payment_id);


--
-- Name: customer_payments_processed customer_payments_processed_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_payments_processed
    ADD CONSTRAINT customer_payments_processed_pkey PRIMARY KEY (payment_id);


--
-- Name: customer_quotes customer_quotes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_quotes
    ADD CONSTRAINT customer_quotes_pkey PRIMARY KEY (customer_quote_id);


--
-- Name: customer_rate_agreements customer_rate_agreements_account_id_customer_id_agreement_y_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_rate_agreements
    ADD CONSTRAINT customer_rate_agreements_account_id_customer_id_agreement_y_key UNIQUE (account_id, customer_id, agreement_year);


--
-- Name: customer_rate_agreements customer_rate_agreements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_rate_agreements
    ADD CONSTRAINT customer_rate_agreements_pkey PRIMARY KEY (rate_agreement_id);


--
-- Name: customer_retainers_and_prepayments customer_retainers_and_prepayments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_retainers_and_prepayments
    ADD CONSTRAINT customer_retainers_and_prepayments_pkey PRIMARY KEY (retainer_id);


--
-- Name: customer_transactions customer_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_transactions
    ADD CONSTRAINT customer_transactions_pkey PRIMARY KEY (transaction_id);


--
-- Name: customer_writeoffs customer_writeoffs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_writeoffs
    ADD CONSTRAINT customer_writeoffs_pkey PRIMARY KEY (writeoff_id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (customer_id);


--
-- Name: invalid_timesheets invalid_timesheets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invalid_timesheets
    ADD CONSTRAINT invalid_timesheets_pkey PRIMARY KEY (invalid_timesheet_error_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);


--
-- Name: recurring_customers recurring_customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurring_customers
    ADD CONSTRAINT recurring_customers_pkey PRIMARY KEY (recurring_customer_id);


--
-- Name: template_downloads template_downloads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.template_downloads
    ADD CONSTRAINT template_downloads_pkey PRIMARY KEY (template_download_id);


--
-- Name: time_tracker_staff time_tracker_staff_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.time_tracker_staff
    ADD CONSTRAINT time_tracker_staff_pkey PRIMARY KEY (id);


--
-- Name: time_tracker_staff time_tracker_staff_unique_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.time_tracker_staff
    ADD CONSTRAINT time_tracker_staff_unique_user UNIQUE (user_id);


--
-- Name: timesheet_entries timesheet_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timesheet_entries
    ADD CONSTRAINT timesheet_entries_pkey PRIMARY KEY (timesheet_entry_id);


--
-- Name: timesheet_errors timesheet_errors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timesheet_errors
    ADD CONSTRAINT timesheet_errors_pkey PRIMARY KEY (timesheet_error_id);


--
-- Name: user_login_log user_login_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_login_log
    ADD CONSTRAINT user_login_log_pkey PRIMARY KEY (user_login_log_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: account_audits_account_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX account_audits_account_idx ON public.account_audits USING btree (account_id, created_at DESC);


--
-- Name: account_audits_customer_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX account_audits_customer_idx ON public.account_audits USING btree (customer_id, created_at DESC);


--
-- Name: ai_call_log_account_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_call_log_account_idx ON public.ai_call_log USING btree (account_id, created_at DESC);


--
-- Name: ai_call_log_entry_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_call_log_entry_idx ON public.ai_call_log USING btree (timesheet_entry_id) WHERE (timesheet_entry_id IS NOT NULL);


--
-- Name: ai_category_training_examples_account_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_category_training_examples_account_idx ON public.ai_category_training_examples USING btree (account_id);


--
-- Name: ai_category_training_examples_txn_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_category_training_examples_txn_idx ON public.ai_category_training_examples USING btree (transaction_id);


--
-- Name: ai_category_training_examples_uploaded_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_category_training_examples_uploaded_idx ON public.ai_category_training_examples USING btree (uploaded_to_vector_store, created_at);


--
-- Name: ai_reviewer_corrections_account_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_reviewer_corrections_account_idx ON public.ai_reviewer_corrections USING btree (account_id, created_at DESC);


--
-- Name: ai_reviewer_corrections_field_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_reviewer_corrections_field_idx ON public.ai_reviewer_corrections USING btree (account_id, field_name, created_at DESC);


--
-- Name: ai_reviewer_corrections_txn_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_reviewer_corrections_txn_idx ON public.ai_reviewer_corrections USING btree (transaction_id);


--
-- Name: ai_time_tracker_transaction_suggestions_account_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_time_tracker_transaction_suggestions_account_idx ON public.ai_time_tracker_transaction_suggestions USING btree (account_id);


--
-- Name: ai_time_tracker_transaction_suggestions_entry_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ai_time_tracker_transaction_suggestions_entry_idx ON public.ai_time_tracker_transaction_suggestions USING btree (timesheet_entry_id);


--
-- Name: customer_payments_processed_account_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_payments_processed_account_idx ON public.customer_payments_processed USING btree (account_id);


--
-- Name: customer_payments_processed_customer_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_payments_processed_customer_idx ON public.customer_payments_processed USING btree (customer_id);


--
-- Name: customer_payments_processed_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_payments_processed_date_idx ON public.customer_payments_processed USING btree (payment_date);


--
-- Name: customer_payments_processed_dedup_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX customer_payments_processed_dedup_idx ON public.customer_payments_processed USING btree (source_file, customer_name, payment_amount);


--
-- Name: customer_payments_processed_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_payments_processed_status_idx ON public.customer_payments_processed USING btree (is_payment_processed, deleted);


--
-- Name: idx_customer_invoices_customer_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_invoices_customer_date ON public.customer_invoices USING btree (customer_id, invoice_date DESC);


--
-- Name: idx_customer_invoices_parent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_invoices_parent ON public.customer_invoices USING btree (parent_invoice_id) WHERE (parent_invoice_id IS NOT NULL);


--
-- Name: idx_customer_payments_customer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_payments_customer ON public.customer_payments USING btree (customer_id, created_at DESC);


--
-- Name: idx_customer_payments_invoice; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_payments_invoice ON public.customer_payments USING btree (customer_invoice_id);


--
-- Name: idx_customer_transactions_customer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_transactions_customer ON public.customer_transactions USING btree (customer_id);


--
-- Name: idx_customer_transactions_invoice; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_transactions_invoice ON public.customer_transactions USING btree (customer_invoice_id);


--
-- Name: idx_customer_transactions_job; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_transactions_job ON public.customer_transactions USING btree (customer_job_id);


--
-- Name: idx_customer_writeoffs_customer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_writeoffs_customer ON public.customer_writeoffs USING btree (customer_id, created_at DESC);


--
-- Name: idx_customer_writeoffs_invoice; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_writeoffs_invoice ON public.customer_writeoffs USING btree (customer_invoice_id);


--
-- Name: idx_rate_agreements_customer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rate_agreements_customer ON public.customer_rate_agreements USING btree (customer_id, agreement_year);


--
-- Name: idx_timesheet_entries_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_timesheet_entries_date ON public.timesheet_entries USING btree (account_id, date);


--
-- Name: notifications_user_unread_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_user_unread_idx ON public.notifications USING btree (user_id, created_at DESC) WHERE (read_at IS NULL);


--
-- Name: template_downloads_account_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX template_downloads_account_idx ON public.template_downloads USING btree (account_id, downloaded_at DESC);


--
-- Name: timesheet_entries_hold_reason_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX timesheet_entries_hold_reason_idx ON public.timesheet_entries USING btree (account_id, hold_reason) WHERE ((is_processed = false) AND (is_deleted = false) AND (hold_reason IS NOT NULL));


--
-- Name: users_active_email_unique_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_active_email_unique_idx ON public.users USING btree (email) WHERE (is_user_active = true);


--
-- Name: account_audits account_audits_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_audits
    ADD CONSTRAINT account_audits_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: account_audits account_audits_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_audits
    ADD CONSTRAINT account_audits_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id) ON DELETE CASCADE;


--
-- Name: account_audits account_audits_run_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_audits
    ADD CONSTRAINT account_audits_run_by_user_id_fkey FOREIGN KEY (run_by_user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;


--
-- Name: account_automation_recipients account_automation_recipients_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_automation_recipients
    ADD CONSTRAINT account_automation_recipients_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: account_automation_recipients account_automation_recipients_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_automation_recipients
    ADD CONSTRAINT account_automation_recipients_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: account_automation_settings account_automation_settings_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_automation_settings
    ADD CONSTRAINT account_automation_settings_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: account_information account_information_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_information
    ADD CONSTRAINT account_information_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: ai_call_log ai_call_log_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_call_log
    ADD CONSTRAINT ai_call_log_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: ai_call_log ai_call_log_timesheet_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_call_log
    ADD CONSTRAINT ai_call_log_timesheet_entry_id_fkey FOREIGN KEY (timesheet_entry_id) REFERENCES public.timesheet_entries(timesheet_entry_id) ON DELETE SET NULL;


--
-- Name: ai_call_log ai_call_log_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_call_log
    ADD CONSTRAINT ai_call_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;


--
-- Name: ai_category_training_examples ai_category_training_examples_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_category_training_examples
    ADD CONSTRAINT ai_category_training_examples_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: ai_category_training_examples ai_category_training_examples_timesheet_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_category_training_examples
    ADD CONSTRAINT ai_category_training_examples_timesheet_entry_id_fkey FOREIGN KEY (timesheet_entry_id) REFERENCES public.timesheet_entries(timesheet_entry_id) ON DELETE SET NULL;


--
-- Name: ai_category_training_examples ai_category_training_examples_transaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_category_training_examples
    ADD CONSTRAINT ai_category_training_examples_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.customer_transactions(transaction_id) ON DELETE SET NULL;


--
-- Name: ai_reviewer_corrections ai_reviewer_corrections_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_reviewer_corrections
    ADD CONSTRAINT ai_reviewer_corrections_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: ai_reviewer_corrections ai_reviewer_corrections_reviewer_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_reviewer_corrections
    ADD CONSTRAINT ai_reviewer_corrections_reviewer_user_id_fkey FOREIGN KEY (reviewer_user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;


--
-- Name: ai_reviewer_corrections ai_reviewer_corrections_timesheet_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_reviewer_corrections
    ADD CONSTRAINT ai_reviewer_corrections_timesheet_entry_id_fkey FOREIGN KEY (timesheet_entry_id) REFERENCES public.timesheet_entries(timesheet_entry_id) ON DELETE SET NULL;


--
-- Name: ai_reviewer_corrections ai_reviewer_corrections_transaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_reviewer_corrections
    ADD CONSTRAINT ai_reviewer_corrections_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.customer_transactions(transaction_id) ON DELETE SET NULL;


--
-- Name: ai_time_tracker_transaction_suggestions ai_time_tracker_transaction_s_suggested_general_work_descr_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_time_tracker_transaction_suggestions
    ADD CONSTRAINT ai_time_tracker_transaction_s_suggested_general_work_descr_fkey FOREIGN KEY (suggested_general_work_description_id) REFERENCES public.customer_general_work_descriptions(general_work_description_id);


--
-- Name: ai_time_tracker_transaction_suggestions ai_time_tracker_transaction_sugg_suggested_job_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_time_tracker_transaction_suggestions
    ADD CONSTRAINT ai_time_tracker_transaction_sugg_suggested_job_category_id_fkey FOREIGN KEY (suggested_job_category_id) REFERENCES public.customer_job_categories(customer_job_category_id);


--
-- Name: ai_time_tracker_transaction_suggestions ai_time_tracker_transaction_suggesti_suggested_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_time_tracker_transaction_suggestions
    ADD CONSTRAINT ai_time_tracker_transaction_suggesti_suggested_customer_id_fkey FOREIGN KEY (suggested_customer_id) REFERENCES public.customers(customer_id);


--
-- Name: ai_time_tracker_transaction_suggestions ai_time_tracker_transaction_suggesti_suggested_job_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_time_tracker_transaction_suggestions
    ADD CONSTRAINT ai_time_tracker_transaction_suggesti_suggested_job_type_id_fkey FOREIGN KEY (suggested_job_type_id) REFERENCES public.customer_job_types(job_type_id);


--
-- Name: ai_time_tracker_transaction_suggestions ai_time_tracker_transaction_suggestions_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_time_tracker_transaction_suggestions
    ADD CONSTRAINT ai_time_tracker_transaction_suggestions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: ai_time_tracker_transaction_suggestions ai_time_tracker_transaction_suggestions_timesheet_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_time_tracker_transaction_suggestions
    ADD CONSTRAINT ai_time_tracker_transaction_suggestions_timesheet_entry_id_fkey FOREIGN KEY (timesheet_entry_id) REFERENCES public.timesheet_entries(timesheet_entry_id) ON DELETE CASCADE;


--
-- Name: customer_general_work_descriptions customer_general_work_descriptions_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_general_work_descriptions
    ADD CONSTRAINT customer_general_work_descriptions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_general_work_descriptions customer_general_work_descriptions_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_general_work_descriptions
    ADD CONSTRAINT customer_general_work_descriptions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: customer_information customer_information_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_information
    ADD CONSTRAINT customer_information_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_information customer_information_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_information
    ADD CONSTRAINT customer_information_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: customer_invoices customer_invoices_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_invoices
    ADD CONSTRAINT customer_invoices_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_invoices customer_invoices_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_invoices
    ADD CONSTRAINT customer_invoices_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: customer_invoices customer_invoices_customer_info_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_invoices
    ADD CONSTRAINT customer_invoices_customer_info_id_fkey FOREIGN KEY (customer_info_id) REFERENCES public.customer_information(customer_info_id);


--
-- Name: customer_job_categories customer_job_categories_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_job_categories
    ADD CONSTRAINT customer_job_categories_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_job_categories customer_job_categories_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_job_categories
    ADD CONSTRAINT customer_job_categories_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: customer_job_types customer_job_types_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_job_types
    ADD CONSTRAINT customer_job_types_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_job_types customer_job_types_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_job_types
    ADD CONSTRAINT customer_job_types_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: customer_job_types customer_job_types_customer_job_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_job_types
    ADD CONSTRAINT customer_job_types_customer_job_category_id_fkey FOREIGN KEY (customer_job_category_id) REFERENCES public.customer_job_categories(customer_job_category_id);


--
-- Name: customer_jobs customer_jobs_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_jobs
    ADD CONSTRAINT customer_jobs_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_jobs customer_jobs_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_jobs
    ADD CONSTRAINT customer_jobs_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: customer_jobs customer_jobs_job_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_jobs
    ADD CONSTRAINT customer_jobs_job_type_id_fkey FOREIGN KEY (job_type_id) REFERENCES public.customer_job_types(job_type_id);


--
-- Name: customer_payments customer_payments_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_payments
    ADD CONSTRAINT customer_payments_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_payments customer_payments_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_payments
    ADD CONSTRAINT customer_payments_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: customer_payments_processed customer_payments_processed_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_payments_processed
    ADD CONSTRAINT customer_payments_processed_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_payments_processed customer_payments_processed_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_payments_processed
    ADD CONSTRAINT customer_payments_processed_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id) ON DELETE SET NULL;


--
-- Name: customer_payments_processed customer_payments_processed_matched_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_payments_processed
    ADD CONSTRAINT customer_payments_processed_matched_customer_id_fkey FOREIGN KEY (matched_customer_id) REFERENCES public.customers(customer_id) ON DELETE SET NULL;


--
-- Name: customer_quotes customer_quotes_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_quotes
    ADD CONSTRAINT customer_quotes_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_quotes customer_quotes_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_quotes
    ADD CONSTRAINT customer_quotes_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: customer_quotes customer_quotes_customer_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_quotes
    ADD CONSTRAINT customer_quotes_customer_job_id_fkey FOREIGN KEY (customer_job_id) REFERENCES public.customer_jobs(customer_job_id);


--
-- Name: customer_rate_agreements customer_rate_agreements_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_rate_agreements
    ADD CONSTRAINT customer_rate_agreements_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_rate_agreements customer_rate_agreements_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_rate_agreements
    ADD CONSTRAINT customer_rate_agreements_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: customer_rate_agreements customer_rate_agreements_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_rate_agreements
    ADD CONSTRAINT customer_rate_agreements_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id) ON DELETE CASCADE;


--
-- Name: customer_retainers_and_prepayments customer_retainers_and_prepayments_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_retainers_and_prepayments
    ADD CONSTRAINT customer_retainers_and_prepayments_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_retainers_and_prepayments customer_retainers_and_prepayments_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_retainers_and_prepayments
    ADD CONSTRAINT customer_retainers_and_prepayments_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: customer_transactions customer_transactions_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_transactions
    ADD CONSTRAINT customer_transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_transactions customer_transactions_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_transactions
    ADD CONSTRAINT customer_transactions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: customer_transactions customer_transactions_customer_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_transactions
    ADD CONSTRAINT customer_transactions_customer_job_id_fkey FOREIGN KEY (customer_job_id) REFERENCES public.customer_jobs(customer_job_id);


--
-- Name: customer_transactions customer_transactions_general_work_description_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_transactions
    ADD CONSTRAINT customer_transactions_general_work_description_id_fkey FOREIGN KEY (general_work_description_id) REFERENCES public.customer_general_work_descriptions(general_work_description_id);


--
-- Name: customer_transactions customer_transactions_logged_for_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_transactions
    ADD CONSTRAINT customer_transactions_logged_for_user_id_fkey FOREIGN KEY (logged_for_user_id) REFERENCES public.users(user_id);


--
-- Name: customer_writeoffs customer_writeoffs_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_writeoffs
    ADD CONSTRAINT customer_writeoffs_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: customer_writeoffs customer_writeoffs_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_writeoffs
    ADD CONSTRAINT customer_writeoffs_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: customers customers_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: invalid_timesheets invalid_timesheets_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invalid_timesheets
    ADD CONSTRAINT invalid_timesheets_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: notifications notifications_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: recurring_customers recurring_customers_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurring_customers
    ADD CONSTRAINT recurring_customers_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: recurring_customers recurring_customers_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurring_customers
    ADD CONSTRAINT recurring_customers_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);


--
-- Name: template_downloads template_downloads_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.template_downloads
    ADD CONSTRAINT template_downloads_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: template_downloads template_downloads_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.template_downloads
    ADD CONSTRAINT template_downloads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: time_tracker_staff time_tracker_staff_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.time_tracker_staff
    ADD CONSTRAINT time_tracker_staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: timesheet_entries timesheet_entries_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timesheet_entries
    ADD CONSTRAINT timesheet_entries_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: timesheet_entries timesheet_entries_matched_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timesheet_entries
    ADD CONSTRAINT timesheet_entries_matched_user_id_fkey FOREIGN KEY (matched_user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;


--
-- Name: timesheet_entries timesheet_entries_suggested_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timesheet_entries
    ADD CONSTRAINT timesheet_entries_suggested_customer_id_fkey FOREIGN KEY (suggested_customer_id) REFERENCES public.customers(customer_id) ON DELETE SET NULL;


--
-- Name: timesheet_entries timesheet_entries_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timesheet_entries
    ADD CONSTRAINT timesheet_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: timesheet_errors timesheet_errors_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timesheet_errors
    ADD CONSTRAINT timesheet_errors_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id) ON DELETE CASCADE;


--
-- Name: timesheet_errors timesheet_errors_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timesheet_errors
    ADD CONSTRAINT timesheet_errors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: user_login_log user_login_log_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_login_log
    ADD CONSTRAINT user_login_log_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id);


--
-- Name: user_login_log user_login_log_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_login_log
    ADD CONSTRAINT user_login_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: users users_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(account_id);


--
-- PostgreSQL database dump complete
--

\unrestrict d9d5rZWKjvzrOomSviqSxExRjo63CZnraaJBSLbJC1CcB45LT28Sf38rqONR8hq

