-- ============================================================
-- DS2 Combined Schema (final state)
-- Tables ordered by foreign key dependencies
-- ============================================================
-- =========================
-- 1. accounts (root table)
-- =========================
CREATE TABLE accounts(
     account_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_name varchar(100) NOT NULL,
     account_type varchar(50) NOT NULL,
     is_account_active boolean NOT NULL,
     account_statement varchar(255),
     account_interest_statement varchar(255),
     account_invoice_interest_rate decimal(10, 2),
     account_invoice_template_option varchar(100),
     account_company_logo bytea,
     created_at timestamp DEFAULT NOW()
);

-- =========================
-- 2. account_information
--    depends on: accounts
-- =========================
CREATE TABLE account_information(
     account_info_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     account_street varchar(255),
     account_city varchar(100),
     account_state varchar(2),
     account_zip varchar(10),
     account_email varchar(255),
     account_phone varchar(20),
     is_this_address_active boolean NOT NULL,
     is_account_physical_address boolean NOT NULL,
     is_account_billing_address boolean NOT NULL,
     is_account_mailing_address boolean NOT NULL,
     created_at timestamp DEFAULT NOW()
);

-- =========================
-- 3. users
--    depends on: accounts
-- =========================
CREATE TABLE users(
     user_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id),
     email varchar(255) NOT NULL,
     display_name varchar(100) NOT NULL,
     cost_rate decimal(10, 2),
     billing_rate decimal(10, 2),
     job_title varchar(50) NOT NULL,
     access_level varchar(50) NOT NULL,
     is_user_active boolean NOT NULL DEFAULT TRUE,
     created_at timestamp DEFAULT NOW()
);

-- =========================
-- 4. user_login_log
--    depends on: users, accounts
-- =========================
CREATE TABLE user_login_log(
     user_login_log_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     user_id integer NOT NULL REFERENCES users(user_id),
     account_id integer NOT NULL REFERENCES accounts(account_id),
     login_ip varchar(50),
     created_at timestamp DEFAULT NOW()
);

-- =========================
-- 5. user_login
--    depends on: accounts, users
-- =========================
CREATE TABLE user_login(
     user_login_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id),
     user_id integer NOT NULL REFERENCES users(user_id),
     user_name varchar(100) NOT NULL,
     password_hash varchar(255) NOT NULL,
     is_login_active boolean NOT NULL DEFAULT TRUE,
     created_at timestamp DEFAULT NOW(),
     updated_at timestamp DEFAULT NOW()
);

-- =========================
-- 6. customers
--    depends on: accounts
-- =========================
CREATE TABLE customers(
     customer_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     business_name varchar(100),
     customer_name varchar(100) NOT NULL,
     display_name varchar(100) NOT NULL,
     is_commercial_customer boolean NOT NULL,
     is_customer_active boolean NOT NULL,
     is_billable boolean NOT NULL,
     is_recurring boolean NOT NULL,
     created_at timestamp DEFAULT NOW()
);

-- =========================
-- 7. customer_information
--    depends on: accounts, customers, users
-- =========================
CREATE TABLE customer_information(
     customer_info_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     customer_id integer NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
     customer_street varchar(255),
     customer_city varchar(100),
     customer_state varchar(2),
     customer_zip varchar(10),
     customer_email varchar(255),
     customer_phone varchar(20),
     is_this_address_active boolean NOT NULL,
     is_customer_physical_address boolean NOT NULL,
     is_customer_billing_address boolean NOT NULL,
     is_customer_mailing_address boolean NOT NULL,
     created_by_user_id integer NOT NULL REFERENCES users(user_id),
     created_at timestamp DEFAULT NOW()
);

-- =========================
-- 8. recurring_customers
--    depends on: accounts, customers, users
-- =========================
CREATE TABLE recurring_customers(
     recurring_customer_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     customer_id integer REFERENCES customers(customer_id) ON DELETE CASCADE,
     subscription_frequency varchar(255) NOT NULL,
     bill_on_date integer NOT NULL,
     recurring_bill_amount DECIMAL(10, 2) NOT NULL,
     start_date date NOT NULL,
     end_date date NULL,
     is_recurring_customer_active boolean NOT NULL,
     created_by_user_id integer NOT NULL REFERENCES users(user_id)
);

-- =========================
-- 9. customer_job_categories
--    depends on: accounts, users
-- =========================
CREATE TABLE customer_job_categories(
     customer_job_category_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     customer_job_category varchar NULL,
     is_job_category_active boolean NOT NULL,
     created_at timestamp DEFAULT NOW(),
     created_by_user_id integer NOT NULL REFERENCES users(user_id)
);

-- =========================
-- 10. customer_job_types
--     depends on: accounts, customer_job_categories, users
-- =========================
CREATE TABLE customer_job_types(
     job_type_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     customer_job_category_id integer NULL REFERENCES customer_job_categories(customer_job_category_id),
     job_description varchar NOT NULL,
     book_rate integer NULL,
     estimated_straight_time integer NULL,
     is_job_type_active boolean NOT NULL,
     created_at timestamp DEFAULT NOW(),
     created_by_user_id integer NOT NULL REFERENCES users(user_id)
);

-- =========================
-- 11. customer_jobs
--     depends on: accounts, customers, customer_job_types, users
-- =========================
CREATE TABLE customer_jobs(
     customer_job_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     parent_job_id integer NULL,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     customer_id integer REFERENCES customers(customer_id) ON DELETE CASCADE,
     job_type_id integer NOT NULL REFERENCES customer_job_types(job_type_id),
     job_quote_amount DECIMAL(10, 2) NULL,
     agreed_job_amount DECIMAL(10, 2) NULL,
     current_job_total DECIMAL(10, 2) NULL,
     job_status DECIMAL(10, 2) NULL,
     is_job_complete boolean NULL,
     is_quote boolean NOT NULL,
     created_at timestamp DEFAULT NOW(),
     created_by_user_id integer NOT NULL REFERENCES users(user_id),
     notes text
);

-- =========================
-- 12. customer_quotes
--     depends on: accounts, customers, customer_jobs, users
-- =========================
CREATE TABLE customer_quotes(
     customer_quote_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     customer_id integer NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
     customer_job_id integer REFERENCES customer_jobs(customer_job_id),
     amount_quoted DECIMAL(10, 2) NOT NULL,
     is_quote_active boolean NOT NULL,
     created_at timestamp DEFAULT NOW(),
     created_by_user_id integer NOT NULL REFERENCES users(user_id),
     notes text
);

-- =========================
-- 13. customer_general_work_descriptions
--     depends on: accounts, users
-- =========================
CREATE TABLE customer_general_work_descriptions(
     general_work_description_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     general_work_description varchar(255) NOT NULL,
     estimated_time integer NOT NULL,
     is_general_work_description_active boolean NOT NULL,
     created_at timestamp DEFAULT NOW(),
     created_by_user_id integer NOT NULL REFERENCES users(user_id)
);

-- =========================
-- 14. customer_invoices
--     depends on: accounts, customers, customer_information, users
-- =========================
CREATE TABLE customer_invoices(
     customer_invoice_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     parent_invoice_id integer NULL,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     customer_id integer NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
     customer_info_id integer NOT NULL REFERENCES customer_information(customer_info_id),
     invoice_number varchar(100),
     invoice_date date NOT NULL,
     due_date date NOT NULL,
     beginning_balance decimal(10, 2) NOT NULL,
     total_payments decimal(10, 2) NOT NULL,
     total_charges decimal(10, 2) NOT NULL,
     total_write_offs decimal(10, 2) NOT NULL,
     total_retainers decimal(10, 2) NOT NULL,
     total_amount_due decimal(10, 2) NOT NULL,
     remaining_balance_on_invoice decimal(10, 2),
     is_invoice_paid_in_full boolean NOT NULL,
     fully_paid_date date NULL,
     created_at timestamp DEFAULT NOW(),
     created_by_user_id integer NOT NULL REFERENCES users(user_id),
     start_date date NULL,
     end_date date NULL,
     invoice_file_location varchar(255) NULL,
     notes text NULL
);

-- =========================
-- 15. customer_transactions
--     depends on: accounts, customers, customer_jobs, customer_general_work_descriptions, users
-- =========================
CREATE TABLE customer_transactions(
     transaction_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     customer_id integer NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
     customer_job_id integer REFERENCES customer_jobs(customer_job_id),
     retainer_id integer NULL,
     customer_invoice_id integer NULL,
     logged_for_user_id integer NOT NULL REFERENCES users(user_id),
     general_work_description_id integer NOT NULL REFERENCES customer_general_work_descriptions(general_work_description_id),
     detailed_work_description text,
     transaction_date date NOT NULL,
     transaction_type varchar(50) NOT NULL,
     quantity DECIMAL(10, 2) NOT NULL DEFAULT 1,
     unit_cost DECIMAL(10, 2) NOT NULL,
     total_transaction DECIMAL(10, 2) NOT NULL,
     is_transaction_billable boolean NOT NULL,
     is_excess_to_subscription boolean NOT NULL,
     created_at timestamp DEFAULT NOW(),
     created_by_user_id integer NOT NULL REFERENCES users(user_id),
     note text
);

-- =========================
-- 16. customer_payments
--     depends on: customers, accounts, users
-- =========================
CREATE TABLE customer_payments(
     payment_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     customer_id integer NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     customer_job_id integer NULL,
     retainer_id integer NULL,
     customer_invoice_id integer NULL,
     payment_date date NOT NULL,
     payment_amount DECIMAL(10, 2) NOT NULL,
     form_of_payment varchar(50),
     payment_reference_number varchar(50),
     is_transaction_billable boolean NOT NULL DEFAULT TRUE,
     created_at timestamp DEFAULT NOW(),
     created_by_user_id integer NOT NULL REFERENCES users(user_id),
     note text
);

-- =========================
-- 17. customer_writeOffs
--     depends on: customers, accounts, users
-- =========================
CREATE TABLE customer_writeOffs(
     writeoff_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     customer_id integer NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     customer_invoice_id integer NULL,
     customer_job_id integer NULL,
     writeoff_date date NOT NULL,
     writeoff_amount DECIMAL(10, 2) NOT NULL,
     transaction_type varchar(50) NOT NULL,
     writeoff_reason varchar(50) NOT NULL,
     created_at timestamp DEFAULT NOW(),
     created_by_user_id integer NOT NULL REFERENCES users(user_id),
     note text
);

-- =========================
-- 18. customer_retainers_and_prepayments
--     depends on: customers, accounts, users
-- =========================
CREATE TABLE customer_retainers_and_prepayments(
     retainer_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     parent_retainer_id integer NULL,
     customer_id integer NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     display_name varchar(100) NULL,
     type_of_hold varchar(50) NOT NULL,
     starting_amount DECIMAL(10, 2) NOT NULL,
     current_amount DECIMAL(10, 2) NOT NULL,
     form_of_payment varchar(50),
     payment_reference_number varchar(50),
     is_retainer_active boolean NOT NULL,
     created_at timestamp DEFAULT NOW(),
     created_by_user_id integer NOT NULL REFERENCES users(user_id),
     note text
);

-- =========================
-- 19. customer_payments_processed
--     depends on: accounts, customers
-- =========================
CREATE TABLE customer_payments_processed(
     payment_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     customer_id integer REFERENCES customers(customer_id) ON DELETE SET NULL,
     matched_customer_id integer REFERENCES customers(customer_id) ON DELETE SET NULL,
     customer_name text NOT NULL DEFAULT '',
     matched_customer_name text NOT NULL DEFAULT '',
     customer_invoice_id text NOT NULL DEFAULT '',
     customer_job_id text NOT NULL DEFAULT '',
     retainer_id text NOT NULL DEFAULT '',
     payment_amount numeric(12, 2),
     payment_reference_number text NOT NULL DEFAULT '',
     payment_date date,
     form_of_payment varchar(30) NOT NULL DEFAULT '',
     is_transaction_billable boolean NOT NULL DEFAULT TRUE,
     is_payment_processed boolean NOT NULL DEFAULT FALSE,
     deleted boolean NOT NULL DEFAULT FALSE,
     date_processed timestamp,
     note text NOT NULL DEFAULT '',
     source_file text NOT NULL DEFAULT '',
     file_location text NOT NULL DEFAULT '',
     created_at timestamp NOT NULL DEFAULT NOW(),
     created_by_user_id integer NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX customer_payments_processed_dedup_idx ON customer_payments_processed(source_file, customer_name, payment_amount);

CREATE INDEX customer_payments_processed_account_idx ON customer_payments_processed(account_id);

CREATE INDEX customer_payments_processed_customer_idx ON customer_payments_processed(customer_id);

CREATE INDEX customer_payments_processed_date_idx ON customer_payments_processed(payment_date);

CREATE INDEX customer_payments_processed_status_idx ON customer_payments_processed(is_payment_processed, deleted);

-- =========================
-- 20. timesheet_entries
--     depends on: accounts, users
-- =========================
CREATE TABLE timesheet_entries(
     timesheet_entry_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     user_id integer NOT NULL REFERENCES users(user_id),
     employee_name text,
     timesheet_name text NOT NULL,
     time_tracker_start_date date NOT NULL,
     time_tracker_end_date date NOT NULL,
     date date NOT NULL,
     entity text,
     category text,
     company_name text,
     first_name text,
     last_name text,
     duration integer NOT NULL,
     notes text NOT NULL,
     is_processed boolean DEFAULT FALSE,
     is_deleted boolean DEFAULT FALSE,
     created_at timestamp DEFAULT NOW()
);

-- =========================
-- 21. ai_time_tracker_transaction_suggestions
--     depends on: accounts, timesheet_entries, customer_job_categories,
--                 customer_job_types, customer_general_work_descriptions, customers
-- =========================
CREATE TABLE ai_time_tracker_transaction_suggestions(
     suggestion_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     timesheet_entry_id integer NOT NULL REFERENCES timesheet_entries(timesheet_entry_id) ON DELETE CASCADE,
     sanitized_notes text NOT NULL,
     suggested_category text,
     suggested_job_category_id integer REFERENCES customer_job_categories(customer_job_category_id),
     suggested_job_type_id integer REFERENCES customer_job_types(job_type_id),
     suggested_general_work_description_id integer REFERENCES customer_general_work_descriptions(general_work_description_id),
     suggested_entity text,
     suggested_customer_id integer REFERENCES customers(customer_id),
     suggested_customer_display_name text,
     ai_confidence numeric(5, 4),
     ai_reason text,
     ai_payload jsonb,
     status varchar(30) NOT NULL DEFAULT 'pending',
     source varchar(30) NOT NULL DEFAULT 'ai',
     created_at timestamp NOT NULL DEFAULT NOW(),
     updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX ai_time_tracker_transaction_suggestions_entry_idx ON ai_time_tracker_transaction_suggestions(timesheet_entry_id);

CREATE INDEX ai_time_tracker_transaction_suggestions_account_idx ON ai_time_tracker_transaction_suggestions(account_id);

-- =========================
-- 22. ai_category_training_examples
--     depends on: accounts, timesheet_entries, customer_transactions
-- =========================
CREATE TABLE ai_category_training_examples(
     training_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     timesheet_entry_id integer REFERENCES timesheet_entries(timesheet_entry_id) ON DELETE SET NULL,
     transaction_id integer REFERENCES customer_transactions(transaction_id) ON DELETE SET NULL,
     original_category text,
     suggested_category text,
     final_category text NOT NULL,
     ai_reason text,
     ai_confidence numeric(5, 4),
     ai_source varchar(30) DEFAULT 'ai',
     original_notes text,
     sanitized_notes text,
     duration_minutes integer,
     entity text,
     uploaded_to_vector_store boolean NOT NULL DEFAULT FALSE,
     uploaded_at timestamp NULL,
     created_at timestamp NOT NULL DEFAULT NOW(),
     updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX ai_category_training_examples_account_idx ON ai_category_training_examples(account_id);

CREATE INDEX ai_category_training_examples_uploaded_idx ON ai_category_training_examples(uploaded_to_vector_store, created_at);

CREATE INDEX ai_category_training_examples_txn_idx ON ai_category_training_examples(transaction_id);

-- =========================
-- 23. ai_request_logs
--     depends on: accounts
-- =========================
CREATE TABLE ai_request_logs(
     ai_request_log_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     request_id varchar(64) NOT NULL,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     user_id integer,
     provider varchar(50) NOT NULL DEFAULT 'openai',
     feature varchar(100) NOT NULL,
     model varchar(100),
     model_cost_tier varchar(50),
     entries_count integer,
     sample_entry_ids jsonb,
     status varchar(30) NOT NULL DEFAULT 'prepared',
     error_message text,
     started_at timestamp NOT NULL DEFAULT NOW(),
     completed_at timestamp,
     created_at timestamp NOT NULL DEFAULT NOW(),
     updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX ai_request_logs_request_id_idx ON ai_request_logs(request_id);

CREATE INDEX ai_request_logs_account_idx ON ai_request_logs(account_id);

CREATE INDEX ai_request_logs_started_idx ON ai_request_logs(started_at);

-- =========================
-- 24. time_tracker_staff
--     depends on: users
-- =========================
CREATE TABLE time_tracker_staff(
     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     user_id integer NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
     is_active boolean NOT NULL DEFAULT TRUE,
     created_at timestamp DEFAULT NOW(),
     CONSTRAINT time_tracker_staff_unique_user UNIQUE (user_id)
);

-- =========================
-- 25. account_automation_settings
--     depends on: accounts
-- =========================
CREATE TABLE account_automation_settings(
     account_automation_setting_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     automation_key varchar(100) NOT NULL,
     is_enabled boolean NOT NULL DEFAULT TRUE,
     created_at timestamp DEFAULT NOW(),
     updated_at timestamp DEFAULT NOW(),
     CONSTRAINT account_automation_settings_unique_account_automation UNIQUE (account_id, automation_key)
);

-- =========================
-- 26. ai_integrations
--     depends on: accounts
-- =========================
CREATE TABLE ai_integrations(
     ai_integration_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     is_enabled boolean NOT NULL DEFAULT FALSE,
     api_key_encrypted text,
     encryption_secret text,
     model varchar(255),
     model_cost_tier varchar(50),
     created_at timestamp DEFAULT NOW(),
     updated_at timestamp DEFAULT NOW(),
     UNIQUE (account_id)
);

-- =========================
-- 27. account_automation_recipients
--     depends on: accounts, users
-- =========================
CREATE TABLE account_automation_recipients(
     account_automation_recipient_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
     automation_key varchar(100) NOT NULL,
     user_id integer NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
     created_at timestamp DEFAULT NOW(),
     updated_at timestamp DEFAULT NOW(),
     CONSTRAINT account_automation_recipients_unique_account_automation_user UNIQUE (account_id, automation_key, user_id)
);

-- =========================
-- Commented-out tables (preserved for reference)
-- =========================
-- CREATE TABLE customer_invoice_snapshot(
--      customer_invoice_snapshot_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--      account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
--      customer_id integer NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
--      customer_invoice_id integer NOT NULL REFERENCES customer_invoices(customer_invoice_id),
--      record_appears_on_invoice_id integer NOT NULL,
--      remaining_balance_on_invoice decimal(10, 2) NOT NULL,
--      invoice_date date NOT NULL,
--      created_at timestamp DEFAULT NOW()
-- );
-- CREATE TABLE customer_adjustments(
--      adjustment_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--      customer_id integer NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
--      account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
--      customer_invoice_id integer NULL,
--      transaction_id integer NULL,
--      customer_job_id integer NULL,
--      adjustment_date date NOT NULL,
--      adjustment_amount DECIMAL(10, 2) NOT NULL,
--      transaction_type varchar(50) NOT NULL,
--      created_at timestamp DEFAULT NOW(),
--      created_by_user_id integer NOT NULL REFERENCES users(user_id),
--      note text
-- );
-- CREATE TABLE customer_notes(
--      customer_note_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--      customer_id integer NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
--      account_id integer NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
--      is_note_active boolean NOT NULL,
--      created_at timestamp DEFAULT NOW(),
--      created_by_user_id integer NOT NULL REFERENCES users(user_id),
--      clearance_level varchar(50) NOT NULL,
--      note_title varchar(100) NOT NULL,
--      note text
-- );
