/**
 * Minimal in-memory fake knex query builder, shared by the transactions/job
 * unit tests so their business logic (sharedTransactionFunctions.js,
 * job-service.js, etc.) can be exercised without a real Postgres connection.
 *
 * It supports exactly the subset of the knex API these modules use:
 *  - both call styles: `db('table')...` and `db.select(...).from('table')...`
 *  - .where/.andWhere with (field, value), (field, operator, value), a plain
 *    object, or a function building a single-level OR group, e.g.
 *    `builder => builder.where('a', x).orWhere('b', x)` (used by
 *    job-service.getJobFamilyIds and retainer-service's chainFilter)
 *  - .whereIn(field, values)
 *  - .orderBy()/.limit() (accepted but not applied - every fixture used by
 *    these tests keys on a unique field, so ordering never changes which
 *    rows match)
 *  - .first() - resolves to a single row or undefined
 *  - .insert(rowOrRows).into(table) / .returning('*') - resolves to the
 *    inserted row(s); without .returning(), awaiting the builder resolves
 *    to the inserted count (matches knex-without-returning semantics)
 *  - .update(data) / .del()|.delete() - same returning-vs-bare-await split
 *  - is thenable (awaitable) as a terminal operation
 *  - .forUpdate()/.forNoKeyUpdate() and .whereRaw()/.andWhereRaw() are accepted and ignored
 *    (no locking; raw predicates are the caller's job to re-check in JS);
 *    inside an OR group, whereNull/orWhereNull match NULL and a raw term
 *    never matches
 *  - db.transaction(fn) / trx.transaction(fn): runs fn with a transaction
 *    handle (`isTransaction === true`) and restores the whole store if fn
 *    rejects, so atomicity (all-or-nothing) is observable; nested calls
 *    behave like savepoints
 *
 * Not a general SQL emulator - only what the code under test actually calls.
 */
const REF = Symbol('fakeDb.ref');

// Postgres auto-assigns these via GENERATED BY DEFAULT AS IDENTITY; the fake
// mirrors that for the tables these tests insert into so a caller that
// relies on the returned row's id (e.g. addNewTransaction chaining a new
// retainer ledger row's id back onto the transaction) sees a real value
// instead of undefined.
const PK_COLUMN_BY_TABLE = {
   customer_jobs: 'customer_job_id',
   customer_job_types: 'job_type_id',
   customer_job_categories: 'customer_job_category_id',
   customer_general_work_descriptions: 'general_work_description_id',
   customer_transactions: 'transaction_id',
   customer_payments: 'payment_id',
   customer_writeoffs: 'writeoff_id',
   customer_retainers_and_prepayments: 'retainer_id'
};

const buildFakeDb = (initialTables = {}) => {
   const store = {};
   for (const [table, rows] of Object.entries(initialTables)) {
      store[table] = rows.map(row => ({ ...row }));
   }

   // Strip a leading "table." qualifier some callers use on field names
   // (e.g. 'customer_transactions.account_id') so lookups match plain rows.
   const unqualify = field => (typeof field === 'string' && field.includes('.') ? field.split('.').pop() : field);

   const clauseMatches = (row, clause) => {
      if (clause.type === 'or-group') return clause.terms.some(term => clauseMatches(row, term));
      if (clause.type === 'never') return false;
      if (clause.op === 'notnull') return row[unqualify(clause.field)] != null;
      const { field, value } = clause;
      const actual = row[unqualify(field)];
      if (value && typeof value === 'object' && value[REF]) return false; // column-ref comparisons are unused by tested code paths
      if (Array.isArray(value) && clause.op === 'in') return value.some(v => String(v) === String(actual));
      if (value === null) return actual === null || actual === undefined;
      return String(actual) === String(value);
   };

   const rowMatches = (row, whereClauses) => whereClauses.every(clause => clauseMatches(row, clause));

   const buildOrGroup = fn => {
      const terms = [];
      const sub = {};
      sub.where = (field, value) => {
         terms.push({ field, value });
         return sub;
      };
      sub.orWhere = sub.where;
      sub.whereNull = field => sub.where(field, null);
      sub.orWhereNull = sub.whereNull;
      // A raw predicate cannot be evaluated here; it never matches on its own.
      sub.whereRaw = () => {
         terms.push({ type: 'never' });
         return sub;
      };
      sub.orWhereRaw = sub.whereRaw;
      fn(sub);
      return { type: 'or-group', terms };
   };

   const builder = initialTable => {
      const state = {
         table: initialTable,
         whereClauses: [],
         limitTo: null, orders: [], columns: [], groups: [], distinctCount: null,
         mode: 'select', // 'select' | 'insert' | 'update' | 'delete'
         insertRows: null,
         updateData: null
      };
      const ensureTable = () => {
         if (!store[state.table]) store[state.table] = [];
         return store[state.table];
      };

      const self = {};
      self.from = t => {
         state.table = t;
         return self;
      };
      self.into = t => {
         state.table = t;
         return self;
      };

      self.where = (a, b, c) => {
         if (typeof a === 'function') {
            state.whereClauses.push(buildOrGroup(a));
            return self;
         }
         if (a && typeof a === 'object') {
            Object.entries(a).forEach(([field, value]) => state.whereClauses.push({ field, value }));
            return self;
         }
         if (c === undefined) state.whereClauses.push({ field: a, value: b });
         else state.whereClauses.push({ field: a, op: b, value: c });
         return self;
      };
      self.andWhere = self.where;
      self.whereIn = (field, values) => {
         state.whereClauses.push({ field, op: 'in', value: values });
         return self;
      };
      // Joins are accepted but not applied (no cross-table projection) - the
      // "refresh the full list" queries these router success paths run use
      // several joins purely for display columns that these tests don't
      // assert on. Real join filtering is out of scope for this fake.
      self.join = () => self;
      self.leftJoin = () => self;
      self.forUpdate = () => self;
      self.forNoKeyUpdate = () => self;
      self.whereRaw = () => self;
      self.andWhereRaw = self.whereRaw;
      self.orderBy = (field, direction = 'asc') => { state.orders.push({ field, direction }); return self; };
      self.whereNotNull = field => { state.whereClauses.push({ field, op: 'notnull' }); return self; };
      self.groupBy = (...fields) => { state.groups = fields; return self; };
      self.countDistinct = spec => { state.distinctCount = spec; return self; };
      self.limit = n => {
         state.limitTo = n;
         return self;
      };
      self.select = (...columns) => { state.columns.push(...columns.flat()); return self; };
      self.clone = () => self;

      self.insert = rowOrRows => {
         state.mode = 'insert';
         state.insertRows = Array.isArray(rowOrRows) ? rowOrRows : [rowOrRows];
         return self;
      };
      self.update = data => {
         state.mode = 'update';
         state.updateData = data;
         return self;
      };
      self.del = () => {
         state.mode = 'delete';
         return self;
      };
      self.delete = self.del;

      const runSelect = () => {
         let rows = ensureTable().filter(row => rowMatches(row, state.whereClauses)).map(row => ({ ...row }));
         rows.sort((a, b) => {
            for (const { field, direction } of state.orders) {
               const av = a[unqualify(field)], bv = b[unqualify(field)];
               if (av === bv) continue;
               if (av == null) return 1; if (bv == null) return -1;
               return (av < bv ? -1 : 1) * (direction === 'desc' ? -1 : 1);
            }
            return 0;
         });
         if (state.distinctCount) {
            const groups = new Map();
            for (const row of rows) {
               const key = JSON.stringify(state.groups.map(k => row[k]));
               if (!groups.has(key)) groups.set(key, []);
               groups.get(key).push(row);
            }
            rows = [...groups.values()].map(group => ({ ...group[0], ...Object.fromEntries(Object.entries(state.distinctCount).map(([alias, col]) => [alias, new Set(group.map(r => r[col])).size])) }));
         }
         if (state.columns.length && state.columns.every(c => typeof c === 'string' && !c.includes('*'))) rows = rows.map(row => Object.fromEntries([...state.columns, ...Object.keys(state.distinctCount || {})].map(c => [unqualify(c), row[unqualify(c)]])));

         return state.limitTo != null ? rows.slice(0, state.limitTo) : rows;
      };
      const runInsert = () =>
         state.insertRows.map(row => {
            const stored = { ...row };
            for (const [key, value] of Object.entries(stored)) if (state.table === 'customer_jobs' && value && value.__raw === 'clock_timestamp()') stored[key] = new Date();
            const pkColumn = PK_COLUMN_BY_TABLE[state.table];
            if (pkColumn && stored[pkColumn] == null) {
               const currentMax = ensureTable().reduce((max, r) => Math.max(max, Number(r[pkColumn]) || 0), 0);
               stored[pkColumn] = currentMax + 1;
            }
            ensureTable().push(stored);
            return { ...stored };
         });
      const runUpdate = () => {
         const rows = ensureTable().filter(row => rowMatches(row, state.whereClauses));
         rows.forEach(row => Object.assign(row, state.updateData));
         return rows.map(row => ({ ...row }));
      };
      const runDelete = () => {
         const removed = ensureTable()
            .filter(row => rowMatches(row, state.whereClauses))
            .map(row => ({ ...row }));
         store[state.table] = ensureTable().filter(row => !rowMatches(row, state.whereClauses));
         return removed;
      };

      self.first = () => {
         const rows = runSelect();
         return Promise.resolve(rows[0]);
      };

      self.returning = () => {
         let result;
         if (state.mode === 'insert') result = runInsert();
         else if (state.mode === 'update') result = runUpdate();
         else if (state.mode === 'delete') result = runDelete();
         else result = runSelect();
         return Promise.resolve(result);
      };

      self.then = (resolve, reject) => {
         let result;
         if (state.mode === 'insert') result = runInsert();
         else if (state.mode === 'update') result = runUpdate().length;
         else if (state.mode === 'delete') result = runDelete().length;
         else result = runSelect();
         return Promise.resolve(result).then(resolve, reject);
      };
      self.catch = reject => self.then(undefined, reject);

      return self;
   };

   // A knex-like handle: callable as db('table'), plus the top-level forms.
   const makeHandle = isTransaction => {
      const handle = table => builder(table);
      // Real knex also supports these directly off the top-level instance
      // (e.g. `db.insert(x).into('table')`, `db.update(x).into('table')...`),
      // not just `db('table').insert(x)` - several services here use that form.
      // Each call must start a FRESH builder, not share state across calls.
      ['select', 'insert', 'update', 'delete', 'del', 'where', 'whereIn'].forEach(method => {
         handle[method] = (...args) => builder(undefined)[method](...args);
      });
      handle.raw = (sql, bindings) => ({ __raw: sql, bindings });
      handle.ref = column => ({ [REF]: true, column });
      handle._store = store;
      handle.isTransaction = isTransaction;
      // All-or-nothing: snapshot the store, restore it if fn rejects. Nested
      // calls (knex savepoints) get the same semantics for their own scope.
      handle.transaction = async fn => {
         const snapshot = structuredClone(store);
         try {
            return await fn(makeHandle(true));
         } catch (err) {
            Object.keys(store).forEach(key => delete store[key]);
            Object.assign(store, snapshot);
            throw err;
         }
      };
      return handle;
   };

   return makeHandle(false);
};

module.exports = { buildFakeDb };
