'use strict';
const express=require('express');const router=express.Router();
const { requireAdmin,requireManagerOrAdmin }=require('../auth/jwt-auth');
const { route,id }=require('../../utils/ledgerAction');const svc=require('./entities-service');const context=require('./entity-context');
const args=req=>({accountId:Number(req.user.account_id),actorId:Number(req.user.user_id),entityId:req.params.entityID,aliasId:req.params.aliasID,reviewId:req.params.entryID,body:req.body || {}});
const action=fn=>route(async req=>{try{return await fn(req);}catch(e){if(e.code==='23505'){e.statusCode=409;e.message='That business name, prefix, alias or request is already in use.';}if(/^P04\d\d$/.test(e.code || ''))e.statusCode=Number(e.code.slice(2));throw e;}});
router.get('/',requireManagerOrAdmin,action(async req=>({entities:await context.entities(req.app.get('db'),req.user.account_id)})));
router.post('/',requireAdmin,action(req=>svc.create(req.app.get('db'),args(req))));
router.get('/balances',requireManagerOrAdmin,action(req=>require('./balances').list(req.app.get('db'),req.user.account_id,req.query.customerId)));
router.get('/review',requireAdmin,action(req=>svc.reviews(req.app.get('db'),req.user.account_id,{limit:Math.min(id(req.query.limit || 100),500),offset:req.query.offset==null || req.query.offset==='0'?0:id(req.query.offset)})));
router.post('/review/:entryID/resolve',requireAdmin,action(req=>svc.resolve(req.app.get('db'),args(req))));
router.get('/transfers',action(async req=>({transfers:await req.app.get('db')('billing_credit_transfers as t').select('t.*','c.display_name as client_name','s.name as source_name','d.name as destination_name').join('customers as c',function(){this.on('c.customer_id','t.customer_id').andOn('c.account_id','t.account_id');}).join('billing_entities as s','s.billing_entity_id','t.billing_entity_id').join('billing_entities as d','d.billing_entity_id','t.destination_entity_id').where('t.account_id',req.user.account_id).orderBy('t.created_at','desc')})));
router.post('/transfers',requireAdmin,action(req=>require('./transfers').create(req.app.get('db'),{...args(req),key:req.get('Idempotency-Key')})));
router.get('/work/:transactionID',requireAdmin,action(async req=>({transaction:await require('./reclassify').read(req.app.get('db'),req.user.account_id,req.params.transactionID)})));
router.post('/work/:transactionID',requireAdmin,action(req=>require('./reclassify').change(req.app.get('db'),{...args(req),transactionId:req.params.transactionID})));
router.get('/cutover',requireAdmin,action(req=>require('./cutover').plan(req.app.get('db'),req.user.account_id)));
router.get('/cutover/amendment',requireAdmin,action(req=>require('./cutover-amendment').plan(req.app.get('db'),req.user.account_id)));
router.post('/cutover/amendment',requireAdmin,action(req=>require('./cutover-amendment').apply(req.app.get('db'),{...args(req),key:req.get('Idempotency-Key')})));
router.get('/cutover/candidates',requireManagerOrAdmin,action(req=>require('./cutover-amendment').candidates(req.app.get('db'),req.user.account_id)));
router.post('/cutover',requireAdmin,action(req=>require('./cutover').apply(req.app.get('db'),{...args(req),key:req.get('Idempotency-Key')})));
router.get('/:entityID',requireAdmin,action(async req=>{const db=req.app.get('db');const entity=await context.requireEntity(db,req.user.account_id,req.params.entityID,{active:false});const aliases=await db('billing_entity_aliases').where({account_id:req.user.account_id,billing_entity_id:entity.billing_entity_id}).orderBy('alias');return {entity,aliases};}));
router.patch('/:entityID',requireAdmin,action(req=>svc.update(req.app.get('db'),args(req))));
router.post('/:entityID/aliases',requireAdmin,action(req=>svc.addAlias(req.app.get('db'),args(req))));
router.delete('/:entityID/aliases/:aliasID',requireAdmin,action(req=>svc.removeAlias(req.app.get('db'),args(req))));
router.get('/:entityID/logo',requireAdmin,action(req=>require('./logo').read(req.app.get('db'),req.user.account_id,req.params.entityID)));
router.post('/:entityID/logo',requireAdmin,action(req=>require('./logo').upload(req.app.get('db'),args(req))));
module.exports=router;
