'use strict';
const {PathScenario,expect,ok}=require('./_path-matrix');
const {today}=require('./_scenario');
const ingest=require('../../src/endpoints/timesheets/auto-ingest-orchestrator');
const runner=require('../../src/endpoints/timesheets/auto-ingest-runner');
const notifications=require('../../src/endpoints/notifications/notifications-service');
const bedrock=require('../../src/ai_integrations/bedrock');
const invoiceService=require('../../src/endpoints/invoice/invoice-service');
const PDFDocument=require('../../src/pdfCreator/pdfkit-tables');
const {S3Client}=require('@aws-sdk/client-s3');

describe('Path matrix: optional ingestion services fail without corrupting billing',function(){
 this.timeout(180000);let s;
 before(async()=>{s=await new PathScenario().boot();});after(()=>s?.close());
 const entry=async(more={})=>(await s.db('timesheet_entries').insert({account_id:1,user_id:3,timesheet_name:'PM-optional.xlsx',employee_name:'Uma User',time_tracker_start_date:today(),time_tracker_end_date:today(),date:today(),duration:6,notes:'Local optional services',company_name:'Alice Anderson',entity:'Clean Room CPA',category:'General Consulting',is_processed:false,is_deleted:false,...more}).returning('*'))[0];
 const run=e=>ingest.processEntries({db:s.db,accountId:1,userId:1,entryIds:[e.timesheet_entry_id],overridesByEntryId:{[e.timesheet_entry_id]:{customer_id:1,customer_job_id:1,general_work_description_id:1,logged_for_user_id:3}}});
 it('confirmed-alias query failure yields an empty map and writes nothing',async()=>{const before=await s.allState();const map=await s.queryFault(/from "timesheet_entries" as "te" inner join/i,()=>ingest._loadConfirmedAliases(s.db,1));expect([...map]).deep.eq([]);expect(await s.allState()).deep.eq(before);});
 it('training-example query failure yields no few-shot examples and writes nothing',async()=>{const before=await s.allState();const rows=await s.queryFault(/from "ai_category_training_examples"/i,()=>ingest._loadFewShots(s.db,1));expect(rows).deep.eq([]);expect(await s.allState()).deep.eq(before);});
 it('legacy negative duration is held for review and never creates a charge',async()=>{const e=await entry({duration:-6}),before=Number((await s.db('customer_transactions').count('* as n').first()).n);const result=await run(e);expect(result.autoInserted).eq(0);expect(result.held).eq(1);const saved=await s.db('timesheet_entries').where({timesheet_entry_id:e.timesheet_entry_id}).first();expect(saved.is_processed).eq(false);expect(saved.hold_reason).eq('missing_required_field');expect(Number((await s.db('customer_transactions').count('* as n').first()).n)).eq(before);});
 it('failed holding-row update and fallback preserve the entire database with diagnostic result',async()=>{const e=await entry({duration:-6}),before=await s.allState();const result=await s.queryFault(/update "timesheet_entries" set/i,()=>run(e));expect(result.autoInserted).eq(0);expect(result.perEntry[0].errorMessage).match(/path-matrix/);expect(await s.allState()).deep.eq(before);});
 it('ingestion notification failure preserves held non-work without creating a charge',async()=>{
  const e=await entry({category:'Vacation',notes:'Vacation'});const before=Number((await s.db('customer_transactions').count('* as n').first()).n);const flag=process.env.TIME_TRACKER_AI_FEATURE_FLAG;process.env.TIME_TRACKER_AI_FEATURE_FLAG='on';
  try{await s.fail(notifications,'insertForUsers',async()=>{const r=await s.post('/timesheets/ai/kickoff/1/1',{entry_ids:[e.timesheet_entry_id]});expect(r.status).eq(202);expect(r.body.status).eq(202);expect(r.body.message).match(/accepted and running/);for(let n=0;n<200;n++){const row=await s.db('timesheet_entries').where({timesheet_entry_id:e.timesheet_entry_id}).first();if(row.ai_attempted_at){await new Promise(r=>setTimeout(r,30));break;}await new Promise(r=>setTimeout(r,5));}});}finally{process.env.TIME_TRACKER_AI_FEATURE_FLAG=flag;}
  // Non-work is deliberately held/nonbillable; no invented AI charge is allowed.
  expect(Number((await s.db('customer_transactions').count('* as n').first()).n)).eq(before);expect((await s.db('timesheet_entries').where({timesheet_entry_id:e.timesheet_entry_id}).first()).is_processed).eq(false);
 });
 it('background ingestion fatal query failure is logged, never a financial write',async()=>{const e=await entry(),before=await s.allState();const flag=process.env.TIME_TRACKER_AI_FEATURE_FLAG;process.env.TIME_TRACKER_AI_FEATURE_FLAG='on';let logged=false;const original=console.error;console.error=(...args)=>{if(String(args[0]).includes('[auto-ingest] fatal'))logged=true;original(...args);};try{await s.queryFault(/select \* from "timesheet_entries" where/i,async()=>{runner.kickOffAutoIngestForEntryIds({db:s.db,accountId:1,userId:1,entryIds:[e.timesheet_entry_id]});for(let n=0;n<200&&!logged;n++)await new Promise(r=>setTimeout(r,5));expect(logged).eq(true);});}finally{console.error=original;process.env.TIME_TRACKER_AI_FEATURE_FLAG=flag;}expect(await s.allState()).deep.eq(before);});
 it('AI response with malformed embedded JSON is rejected without any database writes',async()=>{const before=await s.allState();bedrock._setClientsForTest({bedrockClient:{send:async()=>({body:Buffer.from(JSON.stringify({content:[{type:'text',text:'{malformed}'}]}))})}});let error;try{await bedrock.invokeBedrockClaude({modelId:'local-stub',messages:[],feature:'path-matrix',accountId:1});}catch(e){error=e;}finally{bedrock._setClientsForTest();}expect(error?.message).eq('no_json_object_in_response');expect(await s.allState()).deep.eq(before);});
 it('AI audit-log database failure does not discard the stubbed valid inference',async()=>{const before=await s.allState();bedrock._setClientsForTest({bedrockClient:{send:async()=>({body:Buffer.from(JSON.stringify({content:[{type:'text',text:'{"ok":true}'}]}))})}});try{const result=await s.queryFault(/insert into "ai_call_log"/i,()=>bedrock.invokeBedrockClaude({modelId:'local-stub',messages:[],feature:'path-matrix',accountId:1,db:s.db}));expect(result.json).deep.eq({ok:true});}finally{bedrock._setClientsForTest();}expect(await s.allState()).deep.eq(before);});
 it('invoice draft PDF renderer failure refuses 500 with no ledger or audit writes',async()=>{const c=await s.customer('PM PDF render fail'),j=await s.job(c);await s.work(c,j,100);await s.stub(PDFDocument.prototype,'text',()=>{throw Error('path-matrix PDF failure');},()=>s.refused(()=>s.post('/invoices/createInvoice/1/1',s.configuration([c],{isRoughDraft:true})),500,500,/path-matrix/));});
});
