'use strict';
const {PathScenario,expect,ok}=require('./_path-matrix');
const {today}=require('./_scenario');
const {ComprehendClient}=require('@aws-sdk/client-comprehend');
const recurring=require('../../src/endpoints/recurringCustomer/recurringCustomer-service');
const staff=require('../../src/endpoints/timeTrackerStaff/timeTrackerStaff-service');

describe('Path matrix: concurrent edits and review degradation',function(){
 this.timeout(180000);let s,c,j,w;
 before(async()=>{s=await new PathScenario().boot();c=await s.customer('PM review races');j=await s.job(c);w=await s.work(c,j,10);});after(()=>s?.close());
 const held=async()=> (await s.db('timesheet_entries').insert({account_id:1,user_id:3,timesheet_name:'PM-held.xlsx',time_tracker_start_date:today(),time_tracker_end_date:today(),date:today(),duration:6,notes:'Local held entry',category:'Tax work',is_processed:false,is_deleted:false}).returning('*'))[0];
 const edits={customer_id:1,customer_job_id:1,general_work_description_id:1,transaction_date:today(),logged_for_user_id:3};
 for(const [field,value,msg] of [['customer_id',999999,/Customer.*not found/],['unit_cost',-1,/Rate must be a number/],['unit_cost','NaN',/Rate must be a number/]])it(`PUT held entry | ${field}=${value} refuses 400 and preserves every row`,async()=>{const e=await held();await s.refused(()=>s.put(`/billing-review/${e.timesheet_entry_id}/1/1`,{...edits,[field]:value}),400,undefined,msg);});
 it('PUT cascade edit | missing new customer refuses before writing',()=>s.refused(()=>s.put(`/billing-review/transaction/${w.transaction_id}/1/1`,{updates:{customer_id:999999,customer_job_id:1},confirmCustomerChange:true}),400,undefined,/Customer.*not found/));
 it('PUT transaction | row disappears after owner lookup: legacy refusal without writes',()=>s.queryFault(/select \* from "customer_transactions".*for no key update/i,()=>s.refused(()=>s.editWork(w,{detailedJobDescription:'New notes'}),200,500,/not found/),{empty:true}));
 it('PUT transaction | row changes customer under lock: legacy conflict refusal without writes',async()=>{
  const proto=Object.getPrototypeOf(s.db.client),original=proto.query;
  await s.stub(proto,'query',async function(connection,query,...rest){const result=await original.call(this,connection,query,...rest);if(/select \* from "customer_transactions".*for no key update/i.test(query.sql)){result.response={...result.response,rows:result.response.rows.map(row=>({...row,customer_id:1}))};}return result;},()=>s.refused(()=>s.editWork(w,{detailedJobDescription:'Stale owner'}),200,500,/changed by someone else/));
 });
 for(const operation of ['update','delete'])it(`${operation} recurring | row disappears between route validation and locked service: 500 without writes`,async()=>{
  const payload={accountID:1,userID:1,customerID:c.id,subscriptionFrequency:'Monthly',billingCycle:1,recurringAmount:100,startDate:'2026-01-01',isActive:true};ok(await s.post('/recurringCustomer/createRecurringCustomer/1/1',{recurringCustomer:payload}));const r=await s.db('recurring_customers').where({customer_id:c.id}).orderBy('recurring_customer_id','desc').first();
  await s.queryFault(/select \* from "recurring_customers" where/i,()=>s.refused(()=>operation==='update'?s.put('/recurringCustomer/updateRecurringCustomer',{recurringCustomer:{...payload,recurringCustomerID:r.recurring_customer_id,recurringAmount:75}}):s.del(`/recurringCustomer/deleteRecurringCustomer/1/${r.recurring_customer_id}`),500,undefined,/Recurring customer not found/),{empty:true,after:1});
 });
 it('PUT recurring | conditional update loses its row: 500 with complete rollback',async()=>{await s.queryFault(/update "recurring_customers" set/i,()=>s.refused(()=>s.put('/recurringCustomer/updateRecurringCustomer',{recurringCustomer:{accountID:1,userID:1,recurringCustomerID:1,subscriptionFrequency:'Monthly',billingCycle:1,recurringAmount:75,startDate:'2026-01-01',isActive:true}}),500,undefined,/changed.*refresh/),{empty:true});});
 it('PUT cascade edit | Comprehend failure uses deterministic email redaction and preserves the ledger edit',async()=>{await s.db('customer_transactions').where({transaction_id:w.transaction_id}).update({detailed_work_description:'Contact private@scenario.test'});const r=await s.fail(ComprehendClient.prototype,'send',()=>s.put(`/billing-review/transaction/${w.transaction_id}/1/1`,{updates:{note:'Local private edit',general_work_description_id:2}}));ok(r);const saved=await s.db('customer_transactions').where({transaction_id:w.transaction_id}).first();expect(saved.note).eq('Local private edit');const training=await s.db('ai_category_training_examples').where({transaction_id:w.transaction_id,ai_source:'reviewer_edit'});expect(training).length(1);expect(training[0].sanitized_notes).eq('Contact [REDACTED_EMAIL]');expect(training[0].original_notes).eq(null);});
 it('PUT cascade edit | optional training savepoint failure preserves the requested ledger edit',async()=>{const r=await s.queryFault(/insert into "ai_category_training_examples"/i,()=>s.put(`/billing-review/transaction/${w.transaction_id}/1/1`,{updates:{note:'Local training failure',general_work_description_id:1}}));ok(r);expect((await s.db('customer_transactions').where({transaction_id:w.transaction_id}).first()).general_work_description_id).eq(1);});
 it('PUT cascade edit | optional label lookup failure preserves requested customer move',async()=>{const other=await s.customer('PM label lookup'),job=await s.job(other);const r=await s.queryFault(/select "display_name" from "customers"/i,()=>s.put(`/billing-review/transaction/${w.transaction_id}/1/1`,{updates:{customer_id:other.id,customer_job_id:job.customer_job_id},confirmCustomerChange:true}));ok(r);expect((await s.db('customer_transactions').where({transaction_id:w.transaction_id}).first()).customer_id).eq(other.id);});
 it('POST account | nested account insert failure rolls back both account and address',async()=>{await s.queryFault(/insert into "accounts"/i,()=>s.refused(()=>s.post('/account/createAccount',{account:{account_name:'PM failed account',account_type:'business',is_account_active:true,account_street:'10 Test',account_city:'Phoenix',account_state:'AZ',account_zip:'85001',account_email:'dummy@scenario.test',account_phone:'602-555-0199',is_this_address_active:true,is_account_physical_address:true,is_account_billing_address:true,is_account_mailing_address:true}}),500,undefined,/path-matrix/));});
 it('POST account | unique storage-slug race retries once using a savepoint and saves one account',async()=>{
  const proto=Object.getPrototypeOf(s.db.client),original=proto.query;let attempts=0;const before=Number((await s.db('accounts').count('* as n').first()).n);
  const r=await s.stub(proto,'query',function(connection,query,...rest){if(/insert into "accounts"/i.test(query.sql)&&attempts++===0)return Promise.reject(Object.assign(Error('path-matrix unique collision'),{code:'23505',constraint:'accounts_storage_slug_key'}));return original.call(this,connection,query,...rest);},()=>s.post('/account/createAccount',{account:{account_name:'PM retried account',account_type:'business',is_account_active:true,account_street:'10 Test',account_city:'Phoenix',account_state:'AZ',account_zip:'85001',account_email:'dummy@scenario.test',account_phone:'602-555-0199',is_this_address_active:true,is_account_physical_address:true,is_account_billing_address:true,is_account_mailing_address:true}}));
  ok(r);expect(attempts).eq(2);expect(Number((await s.db('accounts').count('* as n').first()).n)).eq(before+1);const a=await s.db('accounts').where({account_name:'PM retried account'}).first();expect(await s.db('account_information').where({account_id:a.account_id})).length(1);
 });
});
