'use strict';
const {PathScenario,expect,ok}=require('./_path-matrix'),{today}=require('./_scenario'),{randomUUID}=require('crypto');
describe('H2 held credit, cancellation and transfer paths',function(){
 this.timeout(180000);let s,a,b,c,receipt,credit,body;
 const req=(method,path,data,role='sa',key=randomUUID())=>{let r=s.request[method](path).set('Authorization','Bearer '+s.token(role)).set('Idempotency-Key',key);return data===undefined?r:r.send(data);};
 const open=async(entity=a)=>ok(await req('get',`/payments/open-obligations?customerId=${c.id}&entityId=${entity}`));
 const detail=async()=>ok(await req('get',`/payments/receipts/${receipt.receipt_id}`));
 const refuse=(fn,code,pattern=/.+/)=>s.refused(fn,code,code,pattern);
 before(async()=>{s=await new PathScenario().boot();a=(await s.db('billing_entities').where({account_id:1,is_default:true}).first()).billing_entity_id;b=ok(await req('post','/billing-entities',{name:'H2 Credit Advisory',legal_name:'H2 Credit Advisory',invoice_prefix:'HCR',reason:'Separate held credit'})).entity.billing_entity_id;c=await s.customer('H2 Credit Transfers');const state=await open();const result=ok(await req('post','/payments/receipts',{customerId:c.id,entityId:a,amount:100,date:today(),method:'check',reference:'CREDIT100',allocations:[],ledgerFingerprint:state.ledgerFingerprint}));receipt=result.receipt;credit=result.credit;const available=ok(await req('get',`/credits?customerId=${c.id}&entityId=${a}`));body={customerId:c.id,sourceEntityId:a,destinationEntityId:b,creditId:credit.credit_id,amount:40,reason:'Funds for advisory services',ledgerFingerprint:available.ledgerFingerprint};});
 after(async()=>{if(s)await s.close();});
 for(const [label,patch,code]of [['zero',{amount:0},400],['negative',{amount:-1},400],['precision',{amount:'1.001'},400],['same business',()=>({destinationEntityId:a}),400],['missing reason',{reason:''},400],['missing credit',{creditId:2147483646},404],['missing client',{customerId:2147483646},404],['missing destination',{destinationEntityId:2147483646},404],['exceeds available',{amount:101},409],['stale',{ledgerFingerprint:'old'},409]])it(`refuses transfer ${label} without writes`,()=>refuse(()=>req('post','/credits/transfers',{...body,...(typeof patch==='function'?patch():patch)}),code));
 for(const role of ['Manager','Employee'])for(const path of ['credits/transfers','payments/receipts/RECEIPT/cancellations'])it(`${role} cannot ${path}`,async()=>{await s.db('users').where({user_id:3}).update({access_level:role});try{await refuse(()=>req('post','/'+path.replace('RECEIPT',receipt.receipt_id),body,'staff'),403);}finally{await s.db('users').where({user_id:3}).update({access_level:'Employee'});}});
 for(const path of ['payments/open-obligations','credits'])it(`${path} refuses invalid historical cutoffs`,()=>refuse(()=>req('get',`/${path}?customerId=${c.id}&entityId=${a}&asOf=2026-02-30`),400));
 it('receipt reads and transfer history fail without any committed writes',async()=>{await s.queryFault(/select .*payment_receipts/i,()=>refuse(()=>req('get',`/payments/receipts/${receipt.receipt_id}`),500));await s.queryFault(/select .*client_credit_events/i,()=>refuse(()=>req('get','/credits/transfers'),500));});
 it('transfer database failure rolls back its source debit',()=>s.queryFault(/insert into "client_credit_lots"/,()=>refuse(()=>req('post','/credits/transfers',body),500)));
 it('admin moves $40 once without creating a cash receipt, preserving origin lineage',async()=>{const key=randomUUID(),r=ok(await req('post','/credits/transfers',body,'admin',key));const before=await s.allState();expect(ok(await req('post','/credits/transfers',body,'admin',key))).to.deep.equal(r);expect(await s.allState()).to.deep.equal(before);expect((await open()).credits[0].availableCents).to.equal(6000);expect((await open(b)).credits[0].availableCents).to.equal(4000);expect((await s.db('payment_receipts').where({account_id:1,customer_id:c.id}))).to.have.length(1);expect(ok(await req('get','/credits/transfers')).transfers[0].origin_receipt_id).to.equal(receipt.receipt_id);await refuse(()=>req('post','/credits/transfers',{...body,amount:10},'admin',key),409);});
 it('super admin moves another $10 and the destination automatically uses $30 at issuance',async()=>{ok(await req('post','/credits/transfers',{...body,amount:10,ledgerFingerprint:(await open()).ledgerFingerprint}));const job=await s.job(c);await s.work(c,job,30,{entityId:b});const final=await s.finalize([c],{entityId:b});expect(final.invoicesWithDetail[0].heldCreditApplied).to.equal(30);expect(final.invoicesWithDetail[0].invoiceTotal).to.equal(0);expect((await open(b)).credits.reduce((n,l)=>n+l.availableCents,0)).to.equal(2000);});
 it('rejects entry cancellation after credit was finalized in another business',async()=>{const d=await detail();await refuse(()=>req('post',`/payments/receipts/${receipt.receipt_id}/cancellations`,{reason:'Entry mistake',ledgerFingerprint:d.ledgerFingerprint}),409,/finalized/i);});
 it('bounces the complete receipt across both businesses and restores the used $30',async()=>{let d=await detail();ok(await req('post',`/payments/receipts/${receipt.receipt_id}/exceptions`,{condition:'bounced_check',reason:'Returned original check',ledgerFingerprint:d.ledgerFingerprint}));d=await detail();ok(await req('post',`/payments/receipts/${receipt.receipt_id}/reversals`,{reason:'Restore every transferred application',ledgerFingerprint:d.ledgerFingerprint},'admin'));expect((await open()).billedCents).to.equal(0);expect((await open(b)).billedCents).to.equal(3000);expect((await open()).credits.reduce((n,l)=>n+l.availableCents,0)).to.equal(0);expect((await open(b)).credits.reduce((n,l)=>n+l.availableCents,0)).to.equal(0);});
 for(const role of ['admin','sa'])it(`${role} can cancel an unissued erroneous cash receipt once, without an NSF claim`,async()=>{const state=await open(),r=ok(await req('post','/payments/receipts',{customerId:c.id,entityId:a,amount:10,date:today(),method:'cash',reference:'Entry mistake',allocations:[],ledgerFingerprint:state.ledgerFingerprint})).receipt;const d=ok(await req('get',`/payments/receipts/${r.receipt_id}`));await refuse(()=>req('post',`/payments/receipts/${r.receipt_id}/exceptions`,{condition:'bounced_check',reason:'Cannot bounce cash',ledgerFingerprint:d.ledgerFingerprint},role),409);const data={reason:'Wrong amount entered; re-enter correct receipt',ledgerFingerprint:d.ledgerFingerprint},key=randomUUID();await s.queryFault(/insert into "receipt_events"/,()=>refuse(()=>req('post',`/payments/receipts/${r.receipt_id}/cancellations`,data,role,key),500));ok(await req('post',`/payments/receipts/${r.receipt_id}/cancellations`,data,role,key));const before=await s.allState();ok(await req('post',`/payments/receipts/${r.receipt_id}/cancellations`,data,role,key));expect(await s.allState()).to.deep.equal(before);expect(ok(await req('get',`/payments/receipts/${r.receipt_id}`)).events.some(e=>e.kind==='exception_flagged')).to.equal(false);});
 it('credit reads and transfers enforce tenant and authentication boundaries without writes',async()=>{
  await s.foreignFixture();
  await refuse(()=>req('get',`/credits?customerId=${c.id}&entityId=${a}`,undefined,'foreign'),404);
  const before=await s.allState();expect(ok(await req('get','/credits/transfers',undefined,'foreign')).transfers).to.deep.equal([]);expect(await s.allState()).to.deep.equal(before);
  await refuse(()=>req('post','/credits/transfers',body,'foreign'),404);
  for(const [method,path]of [['get',`/credits?customerId=${c.id}&entityId=${a}`],['get','/credits/transfers'],['post','/credits/transfers']])await refuse(()=>s.request[method](path).send(method==='post'?body:undefined),401);
  await s.queryFault(/select .*ar_obligations/i,()=>refuse(()=>req('get',`/credits?customerId=${c.id}&entityId=${a}`),500));
 });

});
