'use strict';
const {PathScenario,expect,ok}=require('./_path-matrix'),{today,ago}=require('./_scenario'),{randomUUID}=require('crypto');
describe('H3 routes: refusals preserve every table and audit event',function(){
 this.timeout(180000);let s,e,other,c,j,invoice,body,credit,memo,refundId,voidId,reversalId;
 const req=(method,path,data,role='sa',key=randomUUID())=>{let r=s.request[method](path);if(role)r=r.set('Authorization','Bearer '+s.token(role));if(key)r=r.set('Idempotency-Key',key);return data===undefined?r:r.send(data);};
 const refusal=(fn,code,pattern=/.+/)=>s.refused(fn,code,code,pattern);
 const load=()=>req('get',`/invoices/${invoice.customer_invoice_id}/corrections`).then(ok);
 const open=()=>req('get',`/payments/open-obligations?customerId=${c.id}&entityId=${e}`).then(ok);
 const base=()=>`/invoices/${invoice.customer_invoice_id}`;
 const memoBody=async()=>({...body,ledgerFingerprint:(await load()).ledgerFingerprint});
 const refundBody=async()=>({entityId:e,amount:10,date:today(),method:'check',reference:'refund10',reason:'Return client credit',ledgerFingerprint:(await open()).ledgerFingerprint});
 const voidBody=()=>({entityId:e,replacementEntityId:e,reason:'Correct the original invoice',date:today(),lines:[{description:'Correct services',amount:120}]});
 before(async()=>{s=await new PathScenario().boot();e=(await s.db('billing_entities').where({account_id:1,is_default:true}).first()).billing_entity_id;other=ok(await req('post','/billing-entities',{name:'Other entity',legal_name:'Other entity',invoice_prefix:'OTHER',reason:'Mistake test'})).entity.billing_entity_id;c=await s.customer('H3 route matrix');j=await s.job(c);await s.work(c,j,100,{entityId:e});await s.finalize([c],{entityId:e});invoice=await s.db('customer_invoices').where({customer_id:c.id}).whereNull('parent_invoice_id').first();body={entityId:e,amount:10,date:today(),reason:'Correct ten dollars',ledgerFingerprint:(await load()).ledgerFingerprint};
 const o=await open();credit=ok(await req('post','/payments/receipts',{customerId:c.id,entityId:e,amount:350,date:today(),method:'check',reference:'H3-held-check',reason:'Hold this deposit for future work',allocations:[],ledgerFingerprint:o.ledgerFingerprint})).credit;body.ledgerFingerprint=(await load()).ledgerFingerprint;});
 after(async()=>{if(s)await s.close();});
 for(const [label,patch,code] of [['zero',{amount:0},400],['negative',{amount:-1},400],['fractional cents',{amount:'1.001'},400],['overflow',{amount:'100000000'},400],['missing reason',{reason:''},400],['nontext reason',{reason:7},400],['long reason',{reason:'a'.repeat(2001)},400],['future date',{date:'2099-01-01'},400],['invalid date',{date:'2026-02-30'},400],['before invoice',{date:ago(1)},400],['missing fingerprint',{ledgerFingerprint:''},400],['stale fingerprint',{ledgerFingerprint:'stale'},409],['over original',{amount:101},409],['missing business',{entityId:null},400]])it(`credit memo rejects ${label}`,async()=>refusal(async()=>req('post',base()+'/credit-memos',{...body,ledgerFingerprint:body.ledgerFingerprint,...patch}),code));
 it('rejects wrong existing business',async()=>refusal(async()=>req('post',base()+'/credit-memos',{...await memoBody(),entityId:other}),409));
 it('requires UUID retry evidence',async()=>refusal(async()=>req('post',base()+'/credit-memos',await memoBody(),'sa','invalid'),400));
 it('refuses unknown source charge and unbalanced line allocation',async()=>{const good=await memoBody();await refusal(async()=>req('post',base()+'/credit-memos',{...good,lines:[{transactionId:2147483646,amount:10}]}),404);const t=await s.db('customer_transactions').where({customer_id:c.id}).first();await refusal(async()=>req('post',base()+'/credit-memos',{...good,lines:[{transactionId:t.transaction_id,amount:9}]}),400);});
 it('storage failure rolls back all memo money, artifacts metadata, and retry evidence',async()=>{const b=await memoBody();await s.fail(require('../../src/utils/s3'),'putObject',()=>refusal(async()=>req('post',base()+'/credit-memos',b),500));});
 it('late database failure rolls back the complete memo',async()=>{const b=await memoBody();await s.queryFault(/insert into "correction_postings"/,()=>refusal(async()=>req('post',base()+'/credit-memos',b),500));});
 it('admin succeeds, repeated key returns exactly one memo, changed input conflicts',async()=>{const b=await memoBody(),key=randomUUID(),first=ok(await req('post',base()+'/credit-memos',b,'admin',key));memo=first.memo;const before=await s.allState();expect(ok(await req('post',base()+'/credit-memos',b,'admin',key))).to.deep.equal(first);expect(await s.allState()).to.deep.equal(before);await refusal(async()=>req('post',base()+'/credit-memos',{...b,amount:9},'admin',key),409);await refusal(async()=>req('post',base()+'/credit-memos',b),409);});
 for(const [label,patch,code] of [['zero',{amount:0},400],['negative',{amount:-1},400],['fractional cents',{amount:'1.001'},400],['over available',{amount:351},409],['missing reason',{reason:''},400],['missing method',{method:''},400],['invalid method',{method:'wire-invented'},400],['missing date',{date:null},400],['missing reference',{reference:''},400],['future date',{date:'2099-01-01'},400],['before credit',{date:ago(1)},400],['missing fingerprint',{ledgerFingerprint:''},400],['stale fingerprint',{ledgerFingerprint:'stale'},409]])it(`refund rejects ${label}`,async()=>{const b=await refundBody();return refusal(async()=>req('post',`/credits/${credit.credit_id}/refunds`,{...b,...patch}),code);});
 it('refund rejects wrong entity and invalid key',async()=>{const b=await refundBody();await refusal(async()=>req('post',`/credits/${credit.credit_id}/refunds`,{...b,entityId:other}),409);await refusal(async()=>req('post',`/credits/${credit.credit_id}/refunds`,b,'sa','invalid'),400);});
 it('refund storage and late database faults leave nothing written',async()=>{const b=await refundBody();await s.fail(require('../../src/utils/s3'),'putObject',()=>refusal(async()=>req('post',`/credits/${credit.credit_id}/refunds`,b),500));await s.queryFault(/insert into "client_credit_events"/,()=>refusal(async()=>req('post',`/credits/${credit.credit_id}/refunds`,b),500));});
 it('super admin refund replays once, stale concurrent refund loses without writes',async()=>{const b=await refundBody(),key=randomUUID(),first=ok(await req('post',`/credits/${credit.credit_id}/refunds`,b,'sa',key)),before=await s.allState();refundId=first.refund.refund_id;expect(ok(await req('post',`/credits/${credit.credit_id}/refunds`,b,'sa',key))).to.deep.equal(first);expect(await s.allState()).to.deep.equal(before);await refusal(async()=>req('post',`/credits/${credit.credit_id}/refunds`,b),409);});
 for(const [label,patch,code] of [['missing reason',{reason:''},400],['no charges',{lines:[]},400],['zero charge',{lines:[{description:'Services',amount:0}]},400],['negative charge',{lines:[{description:'Services',amount:-10}]},400],['missing description',{lines:[{description:'',amount:100}]},400],['foreign work',{lines:[{description:'Services',amount:100,originalTransactionId:2147483646}]},404],['future date',{date:'2099-01-01'},400],['missing entity',{replacementEntityId:null},400],['too many lines',{lines:Array.from({length:101},()=>({description:'Fee',amount:1}))},400],['nonboolean transfer',{transferReleasedCredit:'true'},400],['same business transfer',{transferReleasedCredit:true},400],['pre-invoice date',{date:ago(1)},400],['unknown target',{replacementEntityId:2147483646},404]])for(const suffix of ['/void-rebill/preview','/void-rebill'])it(`${suffix} rejects ${label}`,async()=>refusal(async()=>req('post',base()+suffix,{...voidBody(),previewFingerprint:'x',...patch}),code));
 it('preview is read-only and stale preview is refused',async()=>{const b=voidBody(),before=await s.allState(),p=ok(await req('post',base()+'/void-rebill/preview',b));expect(await s.allState()).to.deep.equal(before);await refusal(async()=>req('post',base()+'/void-rebill',{...b,lines:[{description:'Changed after preview',amount:121}],previewFingerprint:p.previewFingerprint}),409);await refusal(async()=>req('post',base()+'/void-rebill',b),400);});
 it('void/rebill storage and late metadata failures preserve original, money and issue state',async()=>{const b=voidBody(),p=ok(await req('post',base()+'/void-rebill/preview',b)),input={...b,previewFingerprint:p.previewFingerprint};await s.fail(require('../../src/utils/s3'),'putObject',()=>refusal(async()=>req('post',base()+'/void-rebill',input),500));await s.queryFault(/insert into "rebill_links"/,()=>refusal(async()=>req('post',base()+'/void-rebill',input),500));});
 for(const role of ['manager','employee'])it(`${role} cannot apply any new correction or existing adjustment`,async()=>{
  await s.db('users').where({user_id:3}).update({access_level:role});const b=await memoBody(),r=await refundBody();
  for(const [method,path,body] of [['post',base()+'/credit-memos',{entityId:2147483646}],['post',base()+'/void-rebill/preview',{entityId:null}],['post','/writeOffs/createWriteOffs/1/3',{writeOff:{entityId:2147483646}}],['post','/retainers/1/events/1/3',{entityId:2147483646}],['post','/duplicates/1/resolve/1/3',{action:'remove',entityId:2147483646}],['post',base()+'/credit-memos',b],['post',base()+'/void-rebill/preview',voidBody()],['post',base()+'/void-rebill',{...voidBody(),previewFingerprint:'x'}],['post',`/credits/${credit.credit_id}/refunds`,r],['post',`/credit-memos/${memo.memo_id}/reversals`,{...b}],['post','/writeOffs/createWriteOffs/1/3',{writeOff:s.credit(c,1,{entityId:e})}],['put','/writeOffs/updateWriteOffs/1/3',{}],['delete','/writeOffs/deleteWriteOffs/1/3',{}],['post','/retainers/1/events/1/3',{}],['post','/duplicates/1/resolve/1/3',{action:'remove'}],['post','/payments/reversePayment/1/3',{}],['post',base()+'/exceptions/1/3',{}],['post',base()+'/exceptions/1/reverse/1/3',{}],['post',base()+'/exceptions/1/resolve/1/3',{}]])await refusal(async()=>req(method,path,body,'staff'),403);
  await s.db('users').where({user_id:3}).update({access_level:'employee'});
 });
 it('memo reversal validates reason, date, stale state, storage and database failures',async()=>{const b=await memoBody(),path=`/credit-memos/${memo.memo_id}/reversals`;await refusal(async()=>req('post',path,{...b,reason:''}),400);await refusal(async()=>req('post',path,{...b,date:ago(1)}),400);await refusal(async()=>req('post',path,{...b,ledgerFingerprint:'stale'}),409);await s.fail(require('../../src/utils/s3'),'putObject',()=>refusal(async()=>req('post',path,b),500));await s.queryFault(/insert into "correction_postings"/,()=>refusal(async()=>req('post',path,b),500));reversalId=ok(await req('post',path,b,'admin')).reversal.reversal_id;const current=await memoBody();await refusal(async()=>req('post',path,current),409);});
 it('admin finalizes replacement once; repeated key replays and already-voided original refuses',async()=>{const b=voidBody(),p=ok(await req('post',base()+'/void-rebill/preview',b)),input={...b,previewFingerprint:p.previewFingerprint},key=randomUUID(),first=ok(await req('post',base()+'/void-rebill',input,'admin',key));voidId=first.void.void_id;const before=await s.allState();expect(ok(await req('post',base()+'/void-rebill',input,'admin',key))).to.deep.equal(first);expect(await s.allState()).to.deep.equal(before);await refusal(async()=>req('post',base()+'/void-rebill',input),409);await refusal(async()=>req('post',base()+'/credit-memos',await memoBody()),409);});
 const reads=()=>[[`/credit-memos/reversals/${reversalId}/pdf`,/credit_memo_reversals/],[base()+'/corrections',/customer_invoices/],['/credit-memos',/credit_memos/],[`/credit-memos/${memo.memo_id}`,/credit_memos/],[`/credit-memos/${memo.memo_id}/pdf`,/credit_memos/],[`/credits/${credit.credit_id}/refundable`,/client_credit_lots/],['/refunds',/client_refunds/],[`/refunds/${refundId}`,/client_refunds/],[`/refunds/${refundId}/pdf`,/client_refunds/],[`/invoice-voids/${voidId}/pdf`,/invoice_voids/]];
 it('all correction reads succeed and preserve every table',async()=>{for(const [path] of reads()){const before=await s.allState(),r=await req('get',path);expect(r.status,JSON.stringify(r.body)).to.equal(200);expect(await s.allState()).to.deep.equal(before);}});
 it('all correction reads require authentication and roll back database faults',async()=>{for(const [path,pattern] of reads()){await refusal(async()=>req('get',path,undefined,null),401);await s.queryFault(pattern,()=>refusal(async()=>req('get',path),500));}});
 it('all record readers reject malformed and absent identifiers; lists validate pagination',async()=>{for(const id of ['bad','2147483646'])for(const path of [`/credit-memos/reversals/${id}/pdf`,`/invoices/${id}/corrections`,`/credit-memos/${id}`,`/credit-memos/${id}/pdf`,`/credits/${id}/refundable`,`/refunds/${id}`,`/refunds/${id}/pdf`,`/invoice-voids/${id}/pdf`])await refusal(async()=>req('get',path),id==='bad'?400:404);for(const path of ['/credit-memos?page=0','/refunds?customerId=bad'])await refusal(async()=>req('get',path),400);});
 it('artifact storage and tamper failures do not alter money or audit evidence',async()=>{for(const [path]of reads().filter(([p])=>p.endsWith('/pdf'))){await s.fail(require('../../src/utils/s3'),'getObject',()=>refusal(async()=>req('get',path),500));await s.stub(require('../../src/utils/s3'),'getObject',async()=>({body:Buffer.from('wrong bytes')}),()=>refusal(async()=>req('get',path),409));}});
 it('foreign tenants cannot read, download or mutate another account corrections',async()=>{
  await s.foreignFixture();for(const path of ['/credit-memos','/refunds'])expect(ok(await req('get',path,undefined,'foreign')).records).to.deep.equal([]);
  for(const [path]of reads().filter(([p])=>!['/credit-memos','/refunds'].includes(p)))await refusal(()=>req('get',path,undefined,'foreign'),404);
  for(const [path,b]of [[base()+'/credit-memos',body],[base()+'/void-rebill/preview',voidBody()],[base()+'/void-rebill',{...voidBody(),previewFingerprint:'x'}],[`/credits/${credit.credit_id}/refunds`,await refundBody()],[`/credit-memos/${memo.memo_id}/reversals`,await memoBody()]])await refusal(()=>req('post',path,b,'foreign'),404);
 });
 it('all new monetary writes require login and reject unknown source IDs without writes',async()=>{
  for(const [path,b]of [[base()+'/credit-memos',body],[base()+'/void-rebill/preview',voidBody()],[base()+'/void-rebill',{...voidBody(),previewFingerprint:'x'}],[`/credits/${credit.credit_id}/refunds`,await refundBody()],[`/credit-memos/${memo.memo_id}/reversals`,await memoBody()]])await refusal(()=>req('post',path,b,null),401);
  for(const [path,b]of [['/invoices/2147483646/credit-memos',body],['/invoices/2147483646/void-rebill/preview',voidBody()],['/invoices/2147483646/void-rebill',{...voidBody(),previewFingerprint:'x'}],['/credits/2147483646/refunds',await refundBody()],['/credit-memos/2147483646/reversals',await memoBody()]])await refusal(()=>req('post',path,b),404);
 });

 it('unissued and child snapshots cannot be credited or voided',async()=>{
  const child=await s.db('customer_invoices').where({customer_id:c.id}).whereNotNull('parent_invoice_id').first();
  const draftClient=await s.customer('H3 unissued fixture');const raw={...invoice,customer_id:draftClient.id,customer_info_id:draftClient.info.customer_info_id};delete raw.customer_invoice_id;raw.invoice_number='H3-unissued';raw.invoice_file_location=null;raw.created_at=new Date();
  const [draft]=await s.db('customer_invoices').insert(raw).returning('*');
  for(const source of [child,draft])for(const [suffix,b]of [['credit-memos',await memoBody()],['void-rebill/preview',voidBody()],['void-rebill',{...voidBody(),previewFingerprint:'not-issued'}]]){const context=ok(await req('get',`/invoices/${source.customer_invoice_id}/corrections`));await refusal(()=>req('post',`/invoices/${source.customer_invoice_id}/${suffix}`,{...b,ledgerFingerprint:context.ledgerFingerprint}),409,/finalized original/);}
 });
 it('refunded memo credit prevents both memo reversal and source void',async()=>{
  const client=await s.customer('H3 dependent refunded memo'),job=await s.job(client);await s.work(client,job,100,{entityId:e});await s.finalize([client],{entityId:e});
  const inv=await s.db('customer_invoices').where({customer_id:client.id}).whereNull('parent_invoice_id').first(),scope=`customerId=${client.id}&entityId=${e}`;
  let st=ok(await req('get','/payments/open-obligations?'+scope));ok(await req('post','/payments/receipts',{customerId:client.id,entityId:e,amount:100,date:today(),method:'cash',allocations:[{obligationId:st.obligations[0].obligation_id,amount:100}],ledgerFingerprint:st.ledgerFingerprint}));
  st=ok(await req('get','/payments/open-obligations?'+scope));const m=ok(await req('post',`/invoices/${inv.customer_invoice_id}/credit-memos`,{entityId:e,amount:30,reason:'Return overcharge',allowCreditExcess:true,ledgerFingerprint:st.ledgerFingerprint})).memo;
  st=ok(await req('get','/payments/open-obligations?'+scope));const lot=st.credits.find(l=>l.availableCents===3000);ok(await req('post',`/credits/${lot.credit_id}/refunds`,{entityId:e,amount:10,date:today(),method:'cash',reason:'Money returned',ledgerFingerprint:st.ledgerFingerprint},'admin'));
  st=ok(await req('get','/payments/open-obligations?'+scope));await refusal(()=>req('post',`/credit-memos/${m.memo_id}/reversals`,{entityId:e,reason:'Reverse used credit',ledgerFingerprint:st.ledgerFingerprint}),409);
  await refusal(()=>req('post',`/invoices/${inv.customer_invoice_id}/void-rebill/preview`,voidBody()),409);
 });
 it('bounced-check and refunded-credit dependencies cannot silently erase returned money',async()=>{
  const st=await open(),receipt=(await s.db('client_credit_lots').where({credit_id:credit.credit_id}).first()).origin_receipt_id;
  ok(await req('post',`/payments/receipts/${receipt}/exceptions`,{reason:'Bank returned check',condition:'bounced_check',ledgerFingerprint:st.ledgerFingerprint}));
  const r=await refundBody();await refusal(()=>req('post',`/credits/${credit.credit_id}/refunds`,r),409);
  const d=ok(await req('get',`/payments/receipts/${receipt}`));await refusal(()=>req('post',`/payments/receipts/${receipt}/reversals`,{reason:'Attempt reversal after refund',ledgerFingerprint:d.ledgerFingerprint}),409);
 });

 it('pending whole-receipt bounce blocks new memo and rebill before it creates invoice exceptions',async()=>{
  const client=await s.customer('H3 pending bounce correction'),job=await s.job(client);await s.work(client,job,100,{entityId:e});await s.finalize([client],{entityId:e});const inv=await s.db('customer_invoices').where({customer_id:client.id}).whereNull('parent_invoice_id').first();
  let st=ok(await req('get',`/payments/open-obligations?customerId=${client.id}&entityId=${e}`));const receipt=ok(await req('post','/payments/receipts',{customerId:client.id,entityId:e,amount:100,date:today(),method:'check',reference:'H3-NSF',allocations:[{obligationId:st.obligations[0].obligation_id,amount:100}],ledgerFingerprint:st.ledgerFingerprint})).receipt;
  const d=ok(await req('get',`/payments/receipts/${receipt.receipt_id}`));ok(await req('post',`/payments/receipts/${receipt.receipt_id}/exceptions`,{reason:'Returned check',condition:'bounced_check',ledgerFingerprint:d.ledgerFingerprint}));
  st=ok(await req('get',`/invoices/${inv.customer_invoice_id}/corrections`));for(const [suffix,b]of [['credit-memos',{entityId:e,amount:30,reason:'Reduce original charge',allowCreditExcess:true,ledgerFingerprint:st.ledgerFingerprint}],['void-rebill/preview',voidBody()],['void-rebill',{...voidBody(),previewFingerprint:'pending'}]])await refusal(()=>req('post',`/invoices/${inv.customer_invoice_id}/${suffix}`,b),409,/bounced-check/);
 });

});
